import { describe, expect, it } from 'vitest';
import { areAllObligationsPaid, calculationsReady, invoicePaymentMatches, isPaymentHistoryItem, isQuietIssue, isUpcomingPayment, issuePresentation, statusForIssue, statusForMonth } from './accounting';

describe('canonical accounting presentation', () => {
  it('shows pending settlement only when calculations are ready', () => { expect(statusForMonth({ status: 'OPEN', completeness: { status: 'COMPLETE', blockingIssueCount: 0 }, calculations: [{ type: 'RYCZALT', status: 'CURRENT', amount: { amount: '10.00' } }], obligations: [{ title: 'RYCZALT' }], settlement: { fullySettled: false }, issues: [], allowedActions: [] })).toBe('settlement_pending'); expect(statusForMonth({ status: 'OPEN', completeness: { status: 'COMPLETE', blockingIssueCount: 0 }, calculations: [], obligations: [{ title: 'RYCZALT' }, { title: 'VAT' }, { title: 'ZUS' }], settlement: { fullySettled: false }, issues: [], allowedActions: [] })).toBe('calculations_pending'); });
  it('treats only known current calculation states and all obligation calculation types as ready for payment display', () => { expect(calculationsReady([])).toBe(false); expect(calculationsReady([{ type: 'RYCZALT', status: 'CURRENT' }, { type: 'VAT', status: 'CALCULATED' }, { type: 'ZUS', status: 'FROZEN' }], [{ title: 'RYCZALT' }, { title: 'VAT' }, { title: 'ZUS' }])).toBe(true); expect(calculationsReady([{ type: 'ZUS', status: 'CURRENT' }], [{ title: 'RYCZALT' }, { title: 'VAT' }, { title: 'ZUS' }])).toBe(false); expect(calculationsReady([{ type: 'RYCZALT', status: 'DIRTY' }])).toBe(false); expect(calculationsReady([{ type: 'RYCZALT', status: 'STALE' }])).toBe(false); expect(calculationsReady([{ type: 'RYCZALT', status: 'FUTURE_STATUS' }])).toBe(false); });
  it('keeps unknown issue kinds visible as attention', () => { expect(statusForIssue({ id: 'x', code: 'FUTURE', severity: 'WARNING', kind: 'FUTURE_KIND', title: null, message: null, sourceReference: null })).toBe('requires_action'); });
  it('filters only canonical invoice payment statuses without treating NOT_REQUIRED as paid or inventing overdue', () => {
    const base = { id: '1', title: 'Fuel', amount: { amount: '10.00', currency: 'PLN' }, direction: 'PURCHASE' as const, counterparty: 'Fuel', legalName: 'Fuel', alias: null, taxIdentifier: null, documentNumber: null, issueDate: '2026-09-01', currency: 'PLN', importStatus: 'IMPORTED', approvalStatus: 'APPROVED', approvalSource: 'COUNTERPARTY_RULE', paymentVerificationPolicy: 'REQUIRED', source: null, category: 'FUEL', sourceType: null };
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'MATCHED' }, 'PAID')).toBe(true);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'MANUALLY_CONFIRMED' }, 'PAID')).toBe(true);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'PARTIALLY_MATCHED' }, 'UNPAID')).toBe(true);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'UNMATCHED' }, 'UNPAID')).toBe(true);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'NOT_REQUIRED' }, 'NOT_REQUIRED')).toBe(true);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'NOT_REQUIRED' }, 'UNPAID')).toBe(false);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'NOT_REQUIRED' }, 'PAID')).toBe(false);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'OVERDUE' }, 'UNPAID')).toBe(false);
    expect(invoicePaymentMatches({ ...base, paymentStatus: 'FUTURE_STATUS' }, 'PAID')).toBe(false);
    expect(invoicePaymentMatches({ ...base, paymentStatus: null }, 'PAID')).toBe(false);
  });
  it('keeps open obligations out of payment history', () => { expect(isUpcomingPayment({ status: 'OPEN' })).toBe(true); expect(isUpcomingPayment({ status: 'PARTIALLY_PAID' })).toBe(true); expect(isPaymentHistoryItem({ status: 'OPEN' })).toBe(false); expect(isPaymentHistoryItem({ status: 'PAID' })).toBe(true); });
  it('only labels a non-empty obligation list paid when every obligation is settled', () => { expect(areAllObligationsPaid([])).toBe(false); expect(areAllObligationsPaid([{ status: 'PAID' }, { status: 'OVERPAID' }])).toBe(true); expect(areAllObligationsPaid([{ status: 'PAID' }, { status: 'PARTIALLY_PAID' }])).toBe(false); expect(areAllObligationsPaid([{ status: 'FUTURE_STATUS' }])).toBe(false); });
  it('keeps settlement and waiting-for-calculation notices out of attention', () => { expect(isQuietIssue({ code: 'UNSETTLED_OBLIGATION', kind: 'SETTLEMENT', message: 'Payment outstanding' })).toBe(true); expect(isQuietIssue({ code: 'MISSING_CALCULATION', kind: 'BLOCKED', message: 'No calculation is available' })).toBe(true); });
  it('localizes the canonical dirty-calculation issue', () => { expect(issuePresentation({ id: 'calc', code: 'DIRTY_CALCULATION', severity: 'ERROR', kind: 'BLOCKED', title: 'Calculation needs refresh', message: 'The VAT calculation is not current', sourceReference: null })).toMatchObject({ title: 'Obliczenia wymagają odświeżenia', body: 'Przelicz dane dla tego okresu, aby zobaczyć aktualne kwoty.' }); });
});
