import { describe, expect, it } from 'vitest';
import { isPaymentHistoryItem, isQuietIssue, isUpcomingPayment, statusForIssue, statusForMonth, paymentMatches } from './accounting';

describe('canonical accounting presentation', () => {
  it('shows pending settlement without treating a complete period as broken', () => { expect(statusForMonth({ status: 'OPEN', completeness: { status: 'COMPLETE', blockingIssueCount: 0 }, settlement: { fullySettled: false }, issues: [], allowedActions: ['SETTLE'] })).toBe('settlement_pending'); });
  it('keeps unknown issue kinds visible as attention', () => { expect(statusForIssue({ id: 'x', code: 'FUTURE', severity: 'WARNING', kind: 'FUTURE_KIND', title: null, message: null, sourceReference: null })).toBe('requires_action'); });
  it('does not conflate approval with payment filtering', () => { const invoice = { id: '1', title: 'Fuel', amount: { amount: '10.00', currency: 'PLN' }, direction: 'PURCHASE' as const, counterparty: 'Fuel', legalName: 'Fuel', alias: null, taxIdentifier: null, documentNumber: null, issueDate: '2026-09-01', currency: 'PLN', importStatus: 'IMPORTED', approvalStatus: 'APPROVED', approvalSource: 'COUNTERPARTY_RULE', paymentVerificationPolicy: 'NOT_REQUIRED', paymentStatus: 'NOT_REQUIRED', source: null, category: 'FUEL', sourceType: null }; expect(paymentMatches(invoice, 'PAID')).toBe(false); expect(paymentMatches({ ...invoice, paymentStatus: 'MATCHED' }, 'PAID')).toBe(true); });
  it('keeps open obligations out of payment history', () => { expect(isUpcomingPayment({ status: 'OPEN' })).toBe(true); expect(isUpcomingPayment({ status: 'PARTIALLY_PAID' })).toBe(true); expect(isPaymentHistoryItem({ status: 'OPEN' })).toBe(false); expect(isPaymentHistoryItem({ status: 'PAID' })).toBe(true); });
  it('keeps settlement and waiting-for-calculation notices out of attention', () => { expect(isQuietIssue({ code: 'UNSETTLED_OBLIGATION', kind: 'SETTLEMENT', message: 'Payment outstanding' })).toBe(true); expect(isQuietIssue({ code: 'MISSING_CALCULATION', kind: 'BLOCKED', message: 'No calculation is available' })).toBe(true); });
});
