export type UiLocale = 'pl' | 'en';
export const DEFAULT_UI_LOCALE: UiLocale = 'pl';
export const SUPPORTED_UI_LOCALES: UiLocale[] = ['pl', 'en'];
export const intlLocale: Record<UiLocale, string> = { pl: 'pl-PL', en: 'en-GB' };

const translations = {
  pl: {
    auth: { title: 'Investory Accounting', subtitle: 'Zaloguj się, aby zobaczyć dane księgowe', email: 'E-mail', password: 'Hasło', emailPlaceholder: 'nazwa@firma.pl', signIn: 'Zaloguj się', signingIn: 'Logowanie…', or: 'lub', tryDemo: 'Wypróbuj wersję demo', demoNote: 'Demo działa lokalnie na przykładowych danych i nie łączy się z serwerem.', secureNote: 'Token sesji jest przechowywany w bezpiecznym magazynie urządzenia.', errors: { invalid_credentials: 'Nieprawidłowy e-mail lub hasło.', invalid_response: 'Odpowiedź logowania jest nieprawidłowa.', unavailable: 'Nie udało się połączyć z serwerem. Spróbuj ponownie.', unknown: 'Logowanie nie powiodło się. Spróbuj ponownie.' } },
    app: { home: 'Start', invoices: 'Faktury', settlements: 'Rozliczenia', more: 'Więcej' },
    startup: { loading: 'Uruchamianie aplikacji…' },
    common: { all: 'Wszystkie', sales: 'Sprzedaż', purchases: 'Zakupy', filters: 'Filtry', close: 'Zamknij', retry: 'Spróbuj ponownie', loading: 'Ładowanie…', unavailable: 'Nie udało się pobrać danych.', paid: 'Opłacone', unpaid: 'Nieopłacone', partial: 'Częściowo opłacone', notDue: 'Jeszcze niewymagalne', overdue: 'Po terminie', unknown: 'Brak danych', thisMonth: 'Ten miesiąc', previousMonth: 'Poprzedni miesiąc', last3Months: 'Ostatnie 3 miesiące', customRange: 'Własny zakres', back: 'Wstecz', next: 'Dalej', save: 'Zapisz', confirm: 'Potwierdź', cancel: 'Anuluj', select: 'Wybierz', today: 'Dzisiaj' },
    month: { selector: 'Wybrany miesiąc', previous: 'Poprzedni miesiąc', next: 'Następny miesiąc' },
    home: { greeting: 'Dzień dobry', healthyTitle: 'Wszystko załatwione', healthyBody: 'Nie masz teraz nic do zrobienia.', settlementPendingTitle: 'Płatności oczekują', settlementPendingBody: 'Księgowanie okresu jest kompletne, ale zobowiązania nie są jeszcze opłacone.', processingTitle: 'Aktualizujemy dane', processingBody: 'Synchronizacja i obliczenia jeszcze trwają.', unknownTitle: 'Brak danych', unknownBody: 'Nie udało się określić stanu tego miesiąca.', attentionTitle: 'Wymaga Twojej uwagi', attentionBody: 'Sprawdź elementy, które wymagają działania.', informationalTitle: 'Dane są dostępne', informationalBody: 'Nie ma teraz niczego, co wymaga Twojego działania.', amountUnavailable: 'Kwota niedostępna', waitingForData: 'Oczekiwanie na faktury', checkIssue: 'Sprawdź', checkDocument: 'Sprawdź dokument', issueDetails: 'Szczegóły', actionUnavailable: 'Ta czynność nie jest jeszcze dostępna w aplikacji.', period: 'Bieżący okres', revenue: 'Przychód', costs: 'Koszty', income: 'Dochód (szac.)', payments: 'Najbliższe płatności', noPayments: 'Brak płatności w tym okresie', obligations: 'Podsumowanie podatków', outstanding: 'Do zapłaty', actions: 'Działania okresu', attention: 'Wymaga uwagi', noIssues: 'Brak elementów wymagających działania', issueCount: 'rzeczy do sprawdzenia', ryczalt: 'Ryczałt 12%', issueCodes: { unsupportedVatRateTitle: 'Stawka VAT wymaga sprawdzenia', unsupportedVatRateBody: 'Sprawdź dane dokumentu przed dalszym rozliczeniem.', reviewTitle: 'Dane wymagają sprawdzenia', reviewBody: 'Sprawdź brakujące lub niejednoznaczne dane dokumentu.', setupTitle: 'Uzupełnij ustawienia', setupBody: 'Uzupełnij ustawienia wymagane do dalszego rozliczenia.', unknownTitle: 'Nie można określić szczegółów', unknownBody: 'Dostępne dane nie pozwalają opisać tego elementu.' } },
    invoices: { title: 'Faktury', search: 'Szukaj kontrahenta, numeru lub NIP', emptyTitle: 'Brak faktur', emptyBody: 'Tutaj pojawią się Twoje faktury.', filteredTitle: 'Brak wyników', filteredBody: 'Nie znaleźliśmy faktur pasujących do wybranych filtrów.', clearFilters: 'Wyłącz filtry', details: 'Szczegóły faktury', selectedMonth: 'Wybrany miesiąc', previousMonthHeading: 'Poprzedni miesiąc', last3MonthsHeading: 'Ostatnie 3 miesiące', allInSelectedMonth: 'Wszystkie w wybranym miesiącu', counterparty: 'Kontrahent', number: 'Numer faktury', issueDate: 'Data wystawienia', status: 'Status płatności', type: 'Rodzaj', currency: 'Waluta', secondary: 'Dodatkowe informacje', ksef: 'KSeF', source: 'Źródło', category: 'Kategoria', processing: 'Przetwarzanie', review: 'Akceptacja', approval: { approved: 'Zatwierdzono', needsReview: 'Wymaga akceptacji', unknown: 'Status akceptacji nieznany' }, moreOptions: 'Więcej opcji faktury', correction: 'Korekta', manualPaid: 'Potwierdź opłacenie ręcznie', removeManualPaid: 'Usuń ręczne potwierdzenie', manualPaidError: 'Nie udało się zaktualizować statusu płatności.' },
    settlements: { title: 'Rozliczenia', upcoming: 'Najbliższe płatności', history: 'Historia', noPayments: 'Brak nadchodzących płatności w tym okresie', noHistory: 'Brak zakończonych płatności w tym okresie', historyError: 'Nie udało się pobrać historii rozliczeń.', period: 'Okres', dueDate: 'Termin płatności', dueDateUnavailable: '—', amount: 'Kwota', paidAmount: 'Opłacono', remaining: 'Pozostało', remainingShort: 'pozostało', status: 'Status', statusUnavailable: 'Status niedostępny', accountingStatus: 'Status rozliczenia', periodStatus: 'Status okresu', completeness: 'Kompletność księgowania', actions: 'Dostępne działania', reconciliation: 'Uzgodnienie danych' },
    more: { title: 'Więcej', company: 'Dane firmy', counterparties: 'Kontrahenci', systems: 'Połączone systemy', settings: 'Ustawienia', notifications: 'Powiadomienia', reports: 'Eksporty i raporty', help: 'Pomoc i kontakt', signOut: 'Wyloguj się', connected: 'Połączono', notConnected: 'Nie połączono', unknownStatus: 'Brak danych', periodStatus: 'Status okresu', completeness: 'Kompletność', reconciliation: 'Uzgodnienie', demoProfile: 'Profil demonstracyjny', demoDescription: 'Przykładowe dane lokalne. Żadne zmiany nie są wysyłane na serwer.' },
    counterparties: { title: 'Kontrahenci', detail: 'Szczegóły kontrahenta', empty: 'Brak kontrahentów.', error: 'Nie udało się pobrać kontrahentów.', historyError: 'Nie udało się pobrać historii faktur.', noInvoices: 'Brak faktur dla tego kontrahenta.', invoices: 'faktur', rules: 'reguł', rulesPending: 'Reguły będą dostępne po podłączeniu kontraktu Stage 2.', history: 'Historia faktur' },
    settings: { title: 'Ustawienia', language: 'Język', languageDescription: 'Wybierz język aplikacji', polish: 'Polski', english: 'English' },
    actions: { title: 'Co chcesz zrobić?', invoice: 'Wystaw fakturę', cost: 'Dodaj koszt', income: 'Dodaj przychód', close: 'Zamknij', onlyAvailable: 'Dostępne akcje' },
    invoice: { title: 'Wystaw fakturę', client: 'Klient', chooseClient: 'Wybierz klienta', clientSearch: 'Szukaj po nazwie lub NIP', newClient: 'Nowy klient', item: 'Pozycja', description: 'Opis usługi lub produktu', quantity: 'Ilość', unitPrice: 'Cena jednostkowa', currency: 'Waluta', issueDate: 'Data wystawienia', dueDate: 'Termin płatności', review: 'Sprawdź fakturę', total: 'Razem', issue: 'Wystaw fakturę', unavailable: 'Wystawianie faktur nie jest jeszcze obsługiwane przez backend.', clientRequired: 'Wybierz klienta.', descriptionRequired: 'Podaj opis pozycji.', amountRequired: 'Podaj poprawną kwotę.', dateRequired: 'Podaj datę wystawienia.', dueDateRequired: 'Podaj termin płatności.' },
    cost: { title: 'Dodaj koszt', chooseDocument: 'Wybierz dokument', chooseDocumentHint: 'PDF lub zdjęcie faktury', recognize: 'Odczytaj dokument', confirm: 'Dodaj koszt', recognized: 'Odczytane dane', noDocument: 'Wybierz dokument, aby kontynuować.', saved: 'Dokument zapisany do weryfikacji.', duplicate: 'Ta faktura jest już w Twoich dokumentach.', failed: 'Nie udało się odczytać dokumentu. Sprawdź plik i spróbuj ponownie.', unsupportedDirection: 'Wybrany dokument nie jest dokumentem zakupu.', vatTreatment: 'Sposób rozliczenia VAT', domesticPurchase: 'Zakup krajowy', vatRate: 'Stawka VAT', vatRateRequired: 'Podaj stawkę VAT wymaganą do zapisania kosztu.', accountingDecisionRequired: 'Wybierz sposób rozliczenia VAT, aby kontynuować.', errors: { validation_required: 'Dokument wymaga dodatkowych danych do zapisania.', authentication_required: 'Zaloguj się ponownie, aby kontynuować.', authorization_failed: 'Brak uprawnień do wykonania tej operacji.', unavailable: 'Nie udało się połączyć z serwerem. Spróbuj ponownie.', backend_required: 'Ten dokument wymaga decyzji księgowej dostępnej w panelu webowym.', unknown_error: 'Nie udało się zapisać dokumentu. Spróbuj ponownie.' }, treatments: { domestic: 'Zakup krajowy', eu: 'Import usług z UE', nonEu: 'Import usług spoza UE', unknown: 'Opcja wymaga sprawdzenia w panelu webowym' }, country: 'Kraj kontrahenta', backendRequired: 'Ten dokument wymaga decyzji księgowej dostępnej w panelu webowym.' },
    income: { title: 'Dodaj przychód', amount: 'Kwota', date: 'Data', description: 'Opis lub źródło', submit: 'Dodaj przychód', amountRequired: 'Podaj poprawną kwotę.', dateRequired: 'Podaj datę.', descriptionRequired: 'Podaj opis lub źródło.', unavailable: 'Ręczne dodawanie przychodu nie jest jeszcze obsługiwane przez backend.' },
    backend: { actionUnavailable: 'Ta czynność nie jest jeszcze dostępna.', requestFailed: 'Nie udało się wykonać operacji. Sprawdź połączenie i spróbuj ponownie.' },
    automation: { title: 'Automatyzacja', enabled: 'Automatyczne zatwierdzanie', explanation: 'Pozwól Investory automatycznie przetwarzać dokumenty spełniające wymagania backendu i Twoje ustawienia.', maxAmount: 'Maksymalna kwota', maxAmountPlaceholder: '0,00', maxAmountHint: 'Kwota pozostaje dokładna i jest zapisywana jako wartość ustawień.', categories: 'Zaufane kategorie', categoriesPlaceholder: 'np. ACCOUNTING_SERVICE, FUTURE_CATEGORY', categoriesHint: 'Wpisz kanoniczne wartości oddzielone przecinkami. Nie zmieniaj ich na etykiety językowe.', save: 'Zapisz ustawienia', saving: 'Zapisywanie…', errors: { load: 'Nie udało się pobrać ustawień automatyzacji.', save: 'Nie udało się zapisać ustawień. Spróbuj ponownie.', refresh: 'Ustawienia zapisano, ale nie udało się potwierdzić ich aktualnego stanu.', network: 'Nie udało się połączyć z serwerem.', timeout: 'Serwer nie odpowiedział na czas.', authorization: 'Brak uprawnień do zmiany tych ustawień.', validation: 'Sprawdź kwotę i kategorie.', response: 'Odpowiedź serwera jest nieprawidłowa.' } },
    notifications: { title: 'Powiadomienia', description: 'Włącz spokojne przypomnienia o zbliżających się terminach płatności.', paymentReminders: 'Przypomnienia o płatnościach', paymentRemindersHint: 'Przypomnienia są przechowywane tylko na tym urządzeniu.', leadTime: 'Przypomnij', days1: '1 dzień wcześniej', days3: '3 dni wcześniej', days7: '7 dni wcześniej', permissionRevoked: 'Powiadomienia są wyłączone w ustawieniach urządzenia.', loadError: 'Nie udało się pobrać ustawień powiadomień.', error: 'Nie udało się zapisać ustawień lub włączyć powiadomień.' },
    payments: { types: { ppe: 'Ryczałt', vat: 'VAT', zus: 'ZUS', unknown: 'Brak danych' }, status: { paid: 'Opłacone', overdue: 'Po terminie', partial: 'Częściowo opłacone', unpaid: 'Nieopłacone', notDue: 'Jeszcze niewymagalne', unknown: 'Brak danych' } },
    status: { unknown: 'Brak danych', ksefConnected: 'Połączono', ksefNotConfigured: 'Nie skonfigurowano', bankMatched: 'Transakcje dopasowane', bankUnmatched: 'Transakcje wymagają sprawdzenia', bankPending: 'Import w toku', bankFailed: 'Import nie powiódł się', bankNoImport: 'Brak importu', reconciliationHealthy: 'Zgodne', reconciliationMismatch: 'Pozycje wymagają sprawdzenia', reconciliationMissingEvidence: 'Brakuje dokumentów', filingReady: 'Gotowe', filingNeedsAttention: 'Wymaga uwagi', filingPending: 'W przygotowaniu', jpkGenerated: 'Wygenerowano', jpkSubmitted: 'Wysłano', jpkInvalid: 'Nieprawidłowe', jpkMissing: 'Nie wygenerowano', upoReceived: 'Otrzymano', upoRejected: 'Odrzucono', upoMissing: 'Nie otrzymano', documentReceived: 'Otrzymano', documentParsed: 'Przetworzono', documentImported: 'Zaimportowano', documentFailed: 'Przetwarzanie nie powiodło się', documentReviewRequired: 'Wymaga weryfikacji', documentReviewed: 'Zweryfikowano', lifecycle: { open: 'W przygotowaniu', sources_incomplete: 'Brakuje danych', ready_for_review: 'Gotowe do sprawdzenia', issues: 'Wymaga uwagi', confirmed: 'Potwierdzone', filed: 'Złożone', paid: 'Opłacone', settled: 'Rozliczone', locked: 'Zamknięte' } }
  },
  en: {
    auth: { title: 'Investory Accounting', subtitle: 'Sign in to view your accounting data', email: 'Email', password: 'Password', emailPlaceholder: 'name@company.com', signIn: 'Sign in', signingIn: 'Signing in…', or: 'or', tryDemo: 'Try the demo', demoNote: 'The demo runs locally with sample data and does not connect to the server.', secureNote: 'Your session token is stored securely on this device.', errors: { invalid_credentials: 'The email or password is incorrect.', invalid_response: 'The sign-in response was invalid.', unavailable: 'We could not connect to the server. Try again.', unknown: 'Sign-in failed. Try again.' } },
    app: { home: 'Home', invoices: 'Invoices', settlements: 'Settlements', more: 'More' },
    startup: { loading: 'Starting the app…' },
    common: { all: 'All', sales: 'Sales', purchases: 'Purchases', filters: 'Filters', close: 'Close', retry: 'Try again', loading: 'Loading…', unavailable: 'We could not load the data.', paid: 'Paid', unpaid: 'Unpaid', partial: 'Partially paid', notDue: 'Not due yet', overdue: 'Overdue', unknown: 'No data', thisMonth: 'This month', previousMonth: 'Previous month', last3Months: 'Last 3 months', customRange: 'Custom range', back: 'Back', next: 'Next', save: 'Save', confirm: 'Confirm', cancel: 'Cancel', select: 'Select', today: 'Today' },
    month: { selector: 'Selected month', previous: 'Previous month', next: 'Next month' },
    home: { greeting: 'Good morning', healthyTitle: 'All done', healthyBody: 'You have nothing to do right now.', settlementPendingTitle: 'Payments pending', settlementPendingBody: 'Accounting for this period is complete, but the obligations have not been paid yet.', processingTitle: 'Updating your data', processingBody: 'Synchronisation and calculations are still in progress.', unknownTitle: 'No data', unknownBody: 'We could not determine this month’s status.', attentionTitle: 'Needs your attention', attentionBody: 'Review the items that need action.', informationalTitle: 'Information available', informationalBody: 'There is nothing you need to do right now.', amountUnavailable: 'Amount unavailable', waitingForData: 'Waiting for invoices', checkIssue: 'Check', checkDocument: 'Check invoice', issueDetails: 'Details', actionUnavailable: 'This action is not available in the app yet.', period: 'Current period', revenue: 'Revenue', costs: 'Costs', income: 'Estimated income', payments: 'Upcoming payments', noPayments: 'No payments in this period', obligations: 'Tax summary', outstanding: 'Outstanding', actions: 'Period actions', attention: 'Needs attention', noIssues: 'Nothing needs your attention', issueCount: 'items to check', ryczalt: 'Flat-rate tax 12%', issueCodes: { unsupportedVatRateTitle: 'VAT rate needs review', unsupportedVatRateBody: 'Check the invoice details before continuing the accounting process.', reviewTitle: 'Data needs review', reviewBody: 'Check missing or ambiguous data.', setupTitle: 'Complete your settings', setupBody: 'Complete the settings required to continue accounting.', unknownTitle: 'Details unavailable', unknownBody: 'The available data does not describe this item.' } },
    invoices: { title: 'Invoices', search: 'Search counterparty, number or NIP', emptyTitle: 'No invoices', emptyBody: 'Your invoices will appear here.', filteredTitle: 'No results', filteredBody: 'No invoices match the selected filters.', clearFilters: 'Clear filters', details: 'Invoice details', selectedMonth: 'Selected month', previousMonthHeading: 'Previous month', last3MonthsHeading: 'Last 3 months', allInSelectedMonth: 'All in the selected month', counterparty: 'Counterparty', number: 'Invoice number', issueDate: 'Issue date', status: 'Payment status', type: 'Type', currency: 'Currency', secondary: 'Additional information', ksef: 'KSeF', source: 'Source', category: 'Category', processing: 'Processing', review: 'Approval', approval: { approved: 'Approved', needsReview: 'Needs approval', unknown: 'Unknown approval status' }, moreOptions: 'More invoice options', paymentVerification: 'Payment verification', correction: 'Correction', manualPaid: 'Mark as paid manually', removeManualPaid: 'Remove manual payment confirmation', manualPaidError: 'We could not update the payment status.' },
    settlements: { title: 'Settlements', upcoming: 'Upcoming payments', history: 'History', noPayments: 'No upcoming payments for this period', noHistory: 'No completed payments for this period', historyError: 'We could not load settlement history.', period: 'Period', dueDate: 'Due date', dueDateUnavailable: '—', amount: 'Amount', paidAmount: 'Paid', remaining: 'Remaining', remainingShort: 'remaining', status: 'Status', statusUnavailable: 'Status unavailable', accountingStatus: 'Accounting status', periodStatus: 'Period status', completeness: 'Accounting completeness', actions: 'Available actions', reconciliation: 'Data reconciliation' },
    more: { title: 'More', company: 'Company details', counterparties: 'Counterparties', systems: 'Connected systems', settings: 'Settings', notifications: 'Notifications', reports: 'Exports and reports', help: 'Help and contact', signOut: 'Sign out', connected: 'Connected', notConnected: 'Not connected', unknownStatus: 'No data', periodStatus: 'Period status', completeness: 'Completeness', reconciliation: 'Reconciliation', demoProfile: 'Demo profile', demoDescription: 'Local sample data. Changes are not sent to the server.' },
    counterparties: { title: 'Counterparties', detail: 'Counterparty details', empty: 'No counterparties.', error: 'We could not load counterparties.', historyError: 'We could not load invoice history.', noInvoices: 'No invoices for this counterparty.', invoices: 'invoices', rules: 'rules', rulesPending: 'Rules will be available when the Stage 2 contract lands.', history: 'Invoice history' },
    settings: { title: 'Settings', language: 'Language', languageDescription: 'Choose the app language', polish: 'Polski', english: 'English' },
    actions: { title: 'What do you want to do?', invoice: 'Issue an invoice', cost: 'Add a cost', income: 'Add income', close: 'Close', onlyAvailable: 'Available actions' },
    invoice: { title: 'Issue an invoice', client: 'Client', chooseClient: 'Choose a client', clientSearch: 'Search by name or NIP', newClient: 'New client', item: 'Item', description: 'Service or product description', quantity: 'Quantity', unitPrice: 'Unit price', currency: 'Currency', issueDate: 'Issue date', dueDate: 'Due date', review: 'Review invoice', total: 'Total', issue: 'Issue invoice', unavailable: 'Invoice issuing is not yet supported by the backend.', clientRequired: 'Choose a client.', descriptionRequired: 'Enter an item description.', amountRequired: 'Enter a valid amount.', dateRequired: 'Enter the issue date.', dueDateRequired: 'Enter the due date.' },
    cost: { title: 'Add a cost', chooseDocument: 'Choose a document', chooseDocumentHint: 'PDF or invoice photo', recognize: 'Read document', confirm: 'Add cost', recognized: 'Recognised data', noDocument: 'Choose a document to continue.', saved: 'Document saved for review.', duplicate: 'This invoice is already in your documents.', failed: 'We could not read the document. Check the file and try again.', unsupportedDirection: 'The selected document is not a purchase document.', vatTreatment: 'VAT treatment', domesticPurchase: 'Domestic purchase', vatRate: 'VAT rate', vatRateRequired: 'Enter the VAT rate required to save the cost.', accountingDecisionRequired: 'Choose a VAT treatment to continue.', errors: { validation_required: 'This document needs more information before it can be saved.', authentication_required: 'Sign in again to continue.', authorization_failed: 'You are not authorized to perform this operation.', unavailable: 'We could not connect to the server. Try again.', backend_required: 'This document requires an accounting decision in the web panel.', unknown_error: 'We could not save the document. Try again.' }, treatments: { domestic: 'Domestic purchase', eu: 'Import of services from the EU', nonEu: 'Import of services from outside the EU', unknown: 'This option requires review in the web panel' }, country: 'Counterparty country', backendRequired: 'This document requires an accounting decision in the web panel.' },
    income: { title: 'Add income', amount: 'Amount', date: 'Date', description: 'Description or source', submit: 'Add income', amountRequired: 'Enter a valid amount.', dateRequired: 'Enter the date.', descriptionRequired: 'Enter a description or source.', unavailable: 'Manual income is not yet supported by the backend.' },
    backend: { actionUnavailable: 'This action is not available yet.', requestFailed: 'The operation failed. Check your connection and try again.' },
    automation: { title: 'Automation', enabled: 'Automatic approval', explanation: 'Let Investory automatically process documents that meet backend requirements and your settings.', maxAmount: 'Maximum amount', maxAmountPlaceholder: '0.00', maxAmountHint: 'The amount remains exact and is saved as configuration data.', categories: 'Trusted categories', categoriesPlaceholder: 'e.g. ACCOUNTING_SERVICE, FUTURE_CATEGORY', categoriesHint: 'Enter canonical values separated by commas. Do not replace them with translated labels.', save: 'Save settings', saving: 'Saving…', errors: { load: 'We could not load automation settings.', save: 'We could not save the settings. Try again.', refresh: 'The settings were saved, but we could not confirm their current state.', network: 'We could not connect to the server.', timeout: 'The server did not respond in time.', authorization: 'You are not allowed to change these settings.', validation: 'Check the amount and categories.', response: 'The server response was invalid.' } },
    notifications: { title: 'Notifications', description: 'Turn on quiet reminders for approaching payment deadlines.', paymentReminders: 'Payment reminders', paymentRemindersHint: 'Reminders are stored only on this device.', leadTime: 'Remind me', days1: '1 day before', days3: '3 days before', days7: '7 days before', permissionRevoked: 'Notifications are disabled in the device settings.', loadError: 'We could not load notification settings.', error: 'We could not save the settings or enable notifications.' },
    payments: { types: { ppe: 'Ryczałt', vat: 'VAT', zus: 'ZUS', unknown: 'No data' }, status: { paid: 'Paid', overdue: 'Overdue', partial: 'Partially paid', unpaid: 'Unpaid', notDue: 'Not due yet', unknown: 'No data' } },
    status: { unknown: 'No data', ksefConnected: 'Connected', ksefNotConfigured: 'Not configured', bankMatched: 'All transactions matched', bankUnmatched: 'Transactions need review', bankPending: 'Import in progress', bankFailed: 'Import failed', bankNoImport: 'No import', reconciliationHealthy: 'Matches', reconciliationMismatch: 'Items need review', reconciliationMissingEvidence: 'Documents are missing', filingReady: 'Ready', filingNeedsAttention: 'Needs attention', filingPending: 'In preparation', jpkGenerated: 'Generated', jpkSubmitted: 'Submitted', jpkInvalid: 'Invalid', jpkMissing: 'Not generated', upoReceived: 'Received', upoRejected: 'Rejected', upoMissing: 'Not received', documentReceived: 'Received', documentParsed: 'Processed', documentImported: 'Imported', documentFailed: 'Processing failed', documentReviewRequired: 'Needs review', documentReviewed: 'Reviewed', lifecycle: { open: 'In preparation', sources_incomplete: 'Data missing', ready_for_review: 'Ready for review', issues: 'Needs attention', confirmed: 'Confirmed', filed: 'Filed', paid: 'Paid', settled: 'Settled', locked: 'Closed' } }
  }
} as const;

let activeLocale: UiLocale = DEFAULT_UI_LOCALE;
export function setActiveLocale(value: UiLocale): void { activeLocale = value; }
export function getActiveLocale(): UiLocale { return activeLocale; }
export function toIntlLocale(value: UiLocale = activeLocale): string { return intlLocale[value]; }
export function t(path: string, valueLocale: UiLocale = activeLocale): string { const value = path.split('.').reduce<unknown>((current, key) => (current as Record<string, unknown> | undefined)?.[key], translations[valueLocale]); return typeof value === 'string' ? value : path; }
export function formatDate(value: string | null | undefined, options: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short', year: 'numeric' }): string { if (!value) return t('common.unknown'); const date = new Date(`${value.slice(0, 10)}T00:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(toIntlLocale(), options).format(date); }
export function formatMonth(value: string | null | undefined): string {
  if (!value || !/^\d{4}-(0[1-9]|1[0-2])$/.test(value)) return t('common.unknown');
  const date = new Date(`${value}-01T00:00:00`);
  const [year, month] = value.split('-').map(Number);
  return Number.isNaN(date.getTime()) || date.getFullYear() !== year || date.getMonth() + 1 !== month
    ? t('common.unknown')
    : new Intl.DateTimeFormat(toIntlLocale(), { month: 'long', year: 'numeric' }).format(date);
}
function exactDecimalParts(amount: string): { negative: boolean; integer: string; fraction: string } | null {
  const value = amount.trim();
  const match = value.match(/^(?<sign>-)?(?<integer>\d+)(?:\.(?<fraction>\d+))?$/);
  if (!match?.groups?.integer) return null;
  const integer = match.groups.integer.replace(/^0+(?=\d)/, '');
  const rawFraction = match.groups.fraction ?? '';
  const significantFraction = rawFraction.replace(/0+$/, '');
  return { negative: Boolean(match.groups.sign) && (/[1-9]/.test(integer) || /[1-9]/.test(rawFraction)), integer, fraction: significantFraction };
}

function currencyMinorDigits(currency?: string | null): number {
  return 0;
}

function formatExactDecimal(amount: string, currency?: string | null): string | null {
  const parts = exactDecimalParts(amount);
  if (!parts) return null;
  const locale = toIntlLocale();
  const minorDigits = currencyMinorDigits(currency);
  const fraction = parts.fraction.length > minorDigits ? parts.fraction : parts.fraction.padEnd(minorDigits, '0');
  const formatter = currency
    ? new Intl.NumberFormat(locale, { style: 'currency', currency, minimumFractionDigits: minorDigits, maximumFractionDigits: minorDigits })
    : new Intl.NumberFormat(locale, { minimumFractionDigits: minorDigits, maximumFractionDigits: minorDigits });
  const groupedInteger = new Intl.NumberFormat(locale, { useGrouping: true, maximumFractionDigits: 0 }).format(BigInt(parts.integer));
  const template = formatter.formatToParts(parts.negative ? -1 : 1);
  return template.map((part) => part.type === 'integer'
    ? groupedInteger
    : part.type === 'fraction' ? fraction : part.type === 'decimal' && minorDigits === 0 ? ''
    : part.value).join('');
}

export function formatCurrency(amount: string | null | undefined, currency?: string | null): string {
  if (amount == null) return t('common.unknown');
  try {
    return formatExactDecimal(amount, currency) ?? t('common.unknown');
  } catch {
    return t('common.unknown');
  }
}
export type PaymentLabelKey = 'ppe' | 'vat' | 'zus' | 'unknown';
export function paymentLabelKey(type: string): PaymentLabelKey { const normalized = type.toUpperCase(); return normalized === 'RYCZALT' ? 'ppe' : normalized === 'VAT' ? 'vat' : normalized === 'ZUS' ? 'zus' : 'unknown'; }
export function paymentLabel(type: string): string { return t(`payments.types.${paymentLabelKey(type)}`); }
export type PaymentStatusKey = 'paid' | 'overdue' | 'partial' | 'unpaid' | 'notDue' | 'unknown';
export function paymentStatusKey(status: string): PaymentStatusKey { const normalized = status.toUpperCase(); if (['PAID', 'OVERPAID', 'MATCHED', 'MANUALLY_CONFIRMED'].includes(normalized)) return 'paid'; if (normalized === 'OVERDUE') return 'overdue'; if (['PARTIALLY_PAID', 'PARTIAL'].includes(normalized)) return 'partial'; if (['OPEN', 'DUE', 'UNMATCHED'].includes(normalized)) return 'unpaid'; if (normalized === 'NOT_DUE') return 'notDue'; return 'unknown'; }
export function paymentStatusLabel(status: string): string { return t(`payments.status.${paymentStatusKey(status)}`); }
export function costInputLabel(field: string, fallback?: string | null): string { if (field === 'vatTreatment' || field === 'classification') return t('cost.vatTreatment'); if (field === 'vatRate') return t('cost.vatRate'); if (field === 'counterpartyCountry') return t('cost.country'); return fallback || t('common.unknown'); }
export function costOptionLabel(value: string, fallback?: string | null): string { if (value === 'DOMESTIC_PURCHASE') return t('cost.treatments.domestic'); if (value === 'IMPORT_OF_SERVICES_EU') return t('cost.treatments.eu'); if (value === 'IMPORT_OF_SERVICES_NON_EU') return t('cost.treatments.nonEu'); return fallback || t('cost.treatments.unknown'); }
export const translationsByLocale = translations;
