import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../auth/AuthContext';
import { theme } from '../theme/theme';

export function AuthScreen() {
  const { signIn, error } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false);
  async function submit() { if (!email.trim() || !password) return; setBusy(true); try { await signIn(email.trim(), password); } catch { /* context exposes the error */ } finally { setBusy(false); } }
  return <SafeAreaView style={styles.safe}><View style={styles.content}><View style={styles.brand}><Ionicons name="calculator-outline" size={34} color={theme.colors.primary} /><Text style={styles.title}>Investory Accounting</Text><Text style={styles.subtitle}>Sign in to view your accounting data</Text></View><Text style={styles.label}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" autoComplete="email" keyboardType="email-address" style={styles.input} placeholder="you@example.com" placeholderTextColor={theme.colors.textMuted} /><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoComplete="password" style={styles.input} placeholder="Password" placeholderTextColor={theme.colors.textMuted} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable style={[styles.button, (!email.trim() || !password || busy) && styles.disabled]} disabled={!email.trim() || !password || busy} onPress={submit}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Sign in</Text>}</Pressable><Text style={styles.note}>Your session token is stored in the device secure store.</Text></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { flex: 1, justifyContent: 'center', padding: theme.spacing.xl }, brand: { alignItems: 'center', marginBottom: 36 }, title: { color: theme.colors.text, fontSize: 24, fontWeight: '900', marginTop: 12 }, subtitle: { color: theme.colors.textMuted, textAlign: 'center', marginTop: 6 }, label: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700', marginBottom: 6, marginTop: 14 }, input: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, padding: 13, color: theme.colors.text, fontSize: 16 }, error: { color: theme.colors.danger, marginTop: 14 }, button: { alignItems: 'center', backgroundColor: theme.colors.primary, borderRadius: 999, paddingVertical: 13, marginTop: 24 }, disabled: { opacity: 0.5 }, buttonText: { color: '#fff', fontWeight: '800' }, note: { color: theme.colors.textMuted, fontSize: 12, textAlign: 'center', marginTop: 18 } });
