import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { createAccountingRepository } from '../api/config';
import { AccountingLine } from '../model/accounting';
import { formatDate, formatMonth, paymentStatusLabel, t } from '../i18n';
import { formatMoney } from '../utils/money';
import { dateMatches, matchesInvoice, paymentMatches } from '../presentation/accounting';
import { theme } from '../theme/theme';
import { useAccountingMonth } from '../navigation/AccountingMonthContext';
import { MonthSelector } from '../components/MonthSelector';

type Filters = { direction: 'ALL' | 'SALE' | 'PURCHASE'; currency: string; payment: 'ALL' | 'PAID' | 'UNPAID' | 'OVERDUE'; date: 'ALL' | 'THIS_MONTH' | 'PREVIOUS_MONTH' | 'LAST_3_MONTHS' };
const initialFilters: Filters = { direction: 'ALL', currency: 'ALL', payment: 'ALL', date: 'ALL' };

export function DocumentsScreen() {
  const repository = useMemo(() => createAccountingRepository(), []); const { month } = useAccountingMonth();
  const [items, setItems] = useState<AccountingLine[]>([]); const [filters, setFilters] = useState(initialFilters); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [sheet, setSheet] = useState(false); const [selected, setSelected] = useState<AccountingLine | null>(null);
  useEffect(() => { let active = true; setLoading(true); setError(false); setItems([]); const count = filters.date === 'LAST_3_MONTHS' ? 3 : filters.date === 'PREVIOUS_MONTH' ? 2 : 1; repository.getDocumentsForRange(month, count).then((value) => active && setItems(value)).catch(() => active && setError(true)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [repository, month, filters.date]);
  const currencies = [...new Set(items.map((item) => item.currency).filter(Boolean) as string[])]; const filtered = items.filter((item) => filters.direction === 'ALL' || item.direction === filters.direction).filter((item) => filters.currency === 'ALL' || item.currency === filters.currency).filter((item) => matchesInvoice(item, query)).filter((item) => paymentMatches(item, filters.payment)).filter((item) => dateMatches(item, filters.date, month)); const hasFilters = query.trim().length > 0 || JSON.stringify(filters) !== JSON.stringify(initialFilters);
  const clear = () => { setQuery(''); setFilters(initialFilters); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>{t('invoices.title')}</Text><MonthSelector loading={loading} /><View style={styles.search}><Ionicons name="search-outline" size={19} color={theme.colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder={t('invoices.search')} placeholderTextColor={theme.colors.textMuted} style={styles.input} accessibilityLabel={t('invoices.search')} /><Pressable onPress={() => setSheet(true)} accessibilityLabel={t('common.filters')}><Ionicons name="options-outline" size={21} color={theme.colors.primary} /></Pressable></View><View style={styles.chips}>{(['ALL', 'SALE', 'PURCHASE'] as const).map((value) => <Chip key={value} label={value === 'ALL' ? t('common.all') : value === 'SALE' ? t('common.sales') : t('common.purchases')} active={filters.direction === value} onPress={() => setFilters({ ...filters, direction: value })} />)}<Chip label={t('common.filters')} active={hasFilters} onPress={() => setSheet(true)} /></View>{loading ? <ActivityIndicator style={styles.loader} color={theme.colors.primary} /> : error ? <State /> : filtered.length === 0 ? <Empty filtered={hasFilters} onClear={clear} /> : <View><Text style={styles.month}>{formatMonth(month)}</Text><View style={styles.card}>{filtered.map((item, index) => <Pressable key={`${item.id}-${index}`} style={[styles.row, index < filtered.length - 1 && styles.divider]} onPress={() => setSelected(item)} accessibilityRole="button" accessibilityLabel={`${item.counterparty ?? item.title}, ${formatMoney(item.amount)}`}><View style={styles.copy}><Text style={styles.rowTitle}>{item.counterparty ?? item.title}</Text><Text style={styles.meta}>{item.documentNumber ?? t('common.unknown')} · {formatDate(item.issueDate)}</Text></View><View style={styles.right}><Text style={styles.amount}>{formatMoney(item.amount)}</Text><Text style={styles.meta}>{item.paymentStatus ? paymentStatusLabel(item.paymentStatus) : t('common.unknown')}</Text></View></Pressable>)}</View></View>}</ScrollView><FilterSheet visible={sheet} filters={filters} currencies={currencies} onChange={setFilters} onClose={() => setSheet(false)} /><Details item={selected} onClose={() => setSelected(null)} /></SafeAreaView>;
}
function Chip({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.active]} accessibilityRole="button"><Text style={[styles.chipText, active && styles.activeText]}>{label}</Text></Pressable>; }
function Empty({ filtered, onClear }: { filtered: boolean; onClear: () => void }) { return <View style={styles.empty}><Text style={styles.emptyTitle}>{filtered ? t('invoices.filteredTitle') : t('invoices.emptyTitle')}</Text><Text style={styles.meta}>{filtered ? t('invoices.filteredBody') : t('invoices.emptyBody')}</Text>{filtered && <Pressable onPress={onClear}><Text style={styles.link}>{t('invoices.clearFilters')}</Text></Pressable>}</View>; }
function State() { return <View style={styles.empty}><Text style={styles.meta}>{t('common.unavailable')}</Text></View>; }
function FilterSheet({ visible, filters, currencies, onChange, onClose }: { visible: boolean; filters: Filters; currencies: string[]; onChange: (value: Filters) => void; onClose: () => void }) { const set = (value: Partial<Filters>) => onChange({ ...filters, ...value }); return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.header}><Text style={styles.sheetTitle}>{t('common.filters')}</Text><Pressable onPress={onClose} accessibilityLabel={t('common.close')}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Text style={styles.filterTitle}>{t('invoices.issueDate')}</Text><View style={styles.wrap}>{([['ALL', t('common.all')], ['THIS_MONTH', t('common.thisMonth')], ['PREVIOUS_MONTH', t('common.previousMonth')], ['LAST_3_MONTHS', t('common.last3Months')]] as const).map(([value, label]) => <Chip key={value} label={label} active={filters.date === value} onPress={() => set({ date: value })} />)}</View><Text style={styles.filterTitle}>{t('invoices.currency')}</Text><View style={styles.wrap}>{['ALL', ...currencies].map((value) => <Chip key={value} label={value === 'ALL' ? t('common.all') : value} active={filters.currency === value} onPress={() => set({ currency: value })} />)}</View><Text style={styles.filterTitle}>{t('invoices.status')}</Text><View style={styles.wrap}>{(['ALL', 'PAID', 'UNPAID', 'OVERDUE'] as const).map((value) => <Chip key={value} label={value === 'ALL' ? t('common.all') : paymentStatusLabel(value)} active={filters.payment === value} onPress={() => set({ payment: value })} />)}</View><Pressable style={styles.apply} onPress={onClose}><Text style={styles.applyText}>{t('common.close')}</Text></Pressable></View></View></Modal>; }
function Details({ item, onClose }: { item: AccountingLine | null; onClose: () => void }) { if (!item) return null; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.header}><Text style={styles.sheetTitle}>{t('invoices.details')}</Text><Pressable onPress={onClose}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Text style={styles.detailTitle}>{item.counterparty ?? item.title}</Text><Text style={styles.meta}>{t('invoices.number')}: {item.documentNumber ?? t('common.unknown')}</Text><Text style={styles.meta}>{t('invoices.issueDate')}: {formatDate(item.issueDate)}</Text><Text style={styles.meta}>{t('invoices.status')}: {item.paymentStatus ? paymentStatusLabel(item.paymentStatus) : t('common.unknown')}</Text></View></View></Modal>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: 20, paddingBottom: 36 }, title: { color: theme.colors.text, fontSize: 32, fontWeight: '900', marginTop: 8, marginBottom: 14 }, search: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: theme.colors.surface, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 13, marginTop: 14 }, input: { flex: 1, color: theme.colors.text, fontSize: 15 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 }, chip: { minHeight: 36, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 999, paddingHorizontal: 13, paddingVertical: 8, backgroundColor: theme.colors.surface }, active: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary }, chipText: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '700' }, activeText: { color: '#fff' }, loader: { marginTop: 44 }, month: { color: theme.colors.textMuted, fontWeight: '800', marginTop: 26, marginBottom: 8, textTransform: 'capitalize' }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 13 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, copy: { flex: 1 }, rowTitle: { color: theme.colors.text, fontWeight: '800' }, meta: { color: theme.colors.textMuted, fontSize: 12, marginTop: 4 }, right: { alignItems: 'flex-end' }, amount: { color: theme.colors.text, fontWeight: '800' }, empty: { alignItems: 'center', marginTop: 54, gap: 9, paddingHorizontal: 20 }, emptyTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '800' }, link: { color: theme.colors.primary, fontWeight: '800' }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000055' }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, gap: 12 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sheetTitle: { color: theme.colors.text, fontSize: 20, fontWeight: '900' }, filterTitle: { color: theme.colors.text, fontWeight: '800', marginTop: 8 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, apply: { backgroundColor: theme.colors.primary, alignItems: 'center', borderRadius: 999, paddingVertical: 13 }, applyText: { color: '#fff', fontWeight: '800' }, detailTitle: { color: theme.colors.text, fontSize: 22, fontWeight: '900' } });
