import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { AccountingMonth, PaymentLine } from '../model/accounting';
import { createAccountingRepository } from '../api/config';
import { formatDate, formatMonth, paymentLabel, paymentStatusLabel, t } from '../i18n';
import { formatMoney } from '../utils/money';
import { theme } from '../theme/theme';
import { statusForPayment } from '../presentation/accounting';
import { useAccountingMonth } from '../navigation/AccountingMonthContext';

export function HomeScreen() {
  const [month, setMonth] = useState<AccountingMonth | null>(null);
  const [error, setError] = useState(false);
  const [retry, setRetry] = useState(0);
  const repository = useMemo(() => createAccountingRepository(), []);
  const { month: monthId } = useAccountingMonth();
  useEffect(() => { let active = true; repository.getMonth(monthId).then((value) => active && setMonth(value)).catch(() => active && setError(true)); return () => { active = false; }; }, [repository, monthId, retry]);
  if (error) return <State title={t('common.unavailable')} action={t('common.retry')} onPress={() => { setError(false); setMonth(null); setRetry((value) => value + 1); }} />;
  if (!month) return <SafeAreaView style={styles.loading}><ActivityIndicator size="large" color={theme.colors.primary} /></SafeAreaView>;
  const needsAttention = month.attentionCount > 0 || month.payments.some((payment) => statusForPayment(payment) === 'error');
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.greeting}>{t('home.greeting')}</Text><Text style={styles.title}>Investory</Text>
    <View style={[styles.statusCard, needsAttention ? styles.attention : styles.healthy]}><Ionicons name={needsAttention ? 'alert-circle-outline' : 'checkmark-circle-outline'} size={26} color={needsAttention ? theme.colors.warning : theme.colors.success} /><View style={styles.statusCopy}><Text style={styles.statusTitle}>{needsAttention ? t('home.attentionTitle') : t('home.healthyTitle')}</Text><Text style={styles.statusBody}>{needsAttention ? t('home.attentionBody') : t('home.healthyBody')}</Text></View></View>
    <Text style={styles.sectionTitle}>{t('home.period')}</Text><Text style={styles.period}>{formatMonth(month.id)}</Text>
    <View style={styles.summary}><Summary label={t('home.revenue')} value={formatMoney(month.summary.revenue)} /><Summary label={t('home.costs')} value={month.summary.costs ? formatMoney(month.summary.costs) : t('common.unknown')} muted={!month.summary.costs} /><Summary label={t('home.income')} value={month.summary.income ? formatMoney(month.summary.income) : t('common.unknown')} muted={!month.summary.income} /></View>
    <Text style={styles.sectionTitle}>{t('home.payments')}</Text>{month.payments.length ? <View style={styles.card}>{month.payments.map((payment, index) => <PaymentRow key={`${payment.id}-${index}`} payment={payment} />)}</View> : <Text style={styles.empty}>{t('home.noPayments')}</Text>}
  </ScrollView></SafeAreaView>;
}
function Summary({ label, value, muted }: { label: string; value: string; muted?: boolean }) { return <View style={styles.summaryRow}><Text style={styles.summaryLabel}>{label}</Text><Text style={[styles.summaryValue, muted && styles.muted]}>{value}</Text></View>; }
function PaymentRow({ payment }: { payment: PaymentLine }) { const state = statusForPayment(payment); return <View style={styles.paymentRow}><View style={[styles.paymentIcon, state === 'error' && styles.errorIcon]}><Ionicons name="calendar-outline" size={19} color={state === 'error' ? theme.colors.danger : theme.colors.primary} /></View><View style={styles.paymentCopy}><Text style={styles.paymentTitle}>{paymentLabel(payment.title)}</Text><Text style={styles.paymentDate}>{formatDate(payment.dueDate)}</Text></View><View style={styles.paymentAmount}><Text style={styles.amount}>{formatMoney(payment.outstandingAmount)}</Text><Text style={[styles.paymentStatus, state === 'resolved' && styles.resolved, state === 'error' && styles.overdue]}>{paymentStatusLabel(payment.status)}</Text></View></View>; }
function State({ title, action, onPress }: { title: string; action: string; onPress: () => void }) { return <SafeAreaView style={styles.loading}><Ionicons name="cloud-offline-outline" size={34} color={theme.colors.warning} /><Text style={styles.stateTitle}>{title}</Text><Pressable style={styles.retry} onPress={onPress}><Text style={styles.retryText}>{action}</Text></Pressable></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, backgroundColor: theme.colors.background }, content: { padding: 20, paddingBottom: 36 }, greeting: { color: theme.colors.textMuted, fontSize: 15, marginTop: 8 }, title: { color: theme.colors.text, fontSize: 32, fontWeight: '900', marginTop: 2, marginBottom: 22 }, statusCard: { flexDirection: 'row', gap: 12, alignItems: 'center', borderRadius: theme.radius.lg, padding: 18 }, healthy: { backgroundColor: theme.colors.successSoft }, attention: { backgroundColor: theme.colors.warningSoft }, statusCopy: { flex: 1 }, statusTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '900' }, statusBody: { color: theme.colors.textMuted, marginTop: 4 }, sectionTitle: { color: theme.colors.text, fontSize: 19, fontWeight: '900', marginTop: 26 }, period: { color: theme.colors.textMuted, marginTop: 4, textTransform: 'capitalize' }, summary: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, padding: 16, marginTop: 10, borderWidth: 1, borderColor: theme.colors.border }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 }, summaryLabel: { color: theme.colors.textMuted, fontSize: 15 }, summaryValue: { color: theme.colors.text, fontWeight: '800', fontSize: 15 }, muted: { color: theme.colors.textMuted }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden', marginTop: 10 }, paymentRow: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 76, paddingHorizontal: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, paymentIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: theme.colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, errorIcon: { backgroundColor: theme.colors.dangerSoft }, paymentCopy: { flex: 1 }, paymentTitle: { color: theme.colors.text, fontWeight: '800' }, paymentDate: { color: theme.colors.textMuted, marginTop: 4 }, paymentAmount: { alignItems: 'flex-end' }, amount: { color: theme.colors.text, fontWeight: '800' }, paymentStatus: { color: theme.colors.warning, fontSize: 11, fontWeight: '800', marginTop: 4 }, resolved: { color: theme.colors.success }, overdue: { color: theme.colors.danger }, empty: { color: theme.colors.textMuted, marginTop: 12 }, stateTitle: { color: theme.colors.text, fontSize: 17, fontWeight: '800' }, retry: { backgroundColor: theme.colors.primary, borderRadius: 999, paddingHorizontal: 20, paddingVertical: 12 }, retryText: { color: '#fff', fontWeight: '800' } });
