import * as React from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../auth/AuthContext';
import { t } from '../i18n';
import { useLocale } from '../i18n/LocaleContext';
import { theme } from '../theme/theme';
import { createAccountingRepository } from '../api/config';
import { AccountingStatus } from '../model/accounting';
import { bankStatusView, ksefStatusView } from '../presentation/accountingStatus';
import { useAccountingMonth } from '../navigation/AccountingMonthContext';

export function MoreScreen() {
  const { signOut } = useAuth(); const { locale, setLocale } = useLocale(); const [settingsOpen, setSettingsOpen] = React.useState(false); const [status, setStatus] = React.useState<AccountingStatus | null>(null); const [statusLoading, setStatusLoading] = React.useState(true); const repository = React.useMemo(() => createAccountingRepository(), []); const { month, refreshVersion } = useAccountingMonth();
  React.useEffect(() => { let active = true; setStatus(null); setStatusLoading(true); repository.getMonth(month).then((value) => active && setStatus(value.status)).catch(() => active && setStatus(null)).finally(() => active && setStatusLoading(false)); return () => { active = false; }; }, [repository, month, refreshVersion]);
  const ksef = ksefStatusView(status?.ksefStatus); const bank = status ? bankStatusView(status.bankSummary) : null; const ksefLabel = statusLoading ? t('common.loading') : t(ksef.labelKey); const bankLabel = statusLoading ? t('common.loading') : t(bank?.labelKey ?? 'status.unknown');
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{t('more.title')}</Text><Group rows={[['business-outline', t('more.company')], ['link-outline', t('more.systems')], ['settings-outline', t('more.settings'), () => setSettingsOpen(true)], ['download-outline', t('more.reports')], ['help-circle-outline', t('more.help')]]} /><View style={styles.systems}><Text style={styles.systemTitle}>{t('more.systems')}</Text><System name={t('more.ksef')} status={ksefLabel} state={statusLoading ? 'pending' : ksef.state} /><System name={t('more.bank')} status={bankLabel} state={statusLoading ? 'pending' : bank?.state ?? 'unknown'} /><System name={t('more.zus')} status={t('more.unknownStatus')} state="unknown" /></View><Pressable style={styles.signOut} onPress={signOut} accessibilityRole="button" accessibilityLabel={t('more.signOut')}><Ionicons name="log-out-outline" size={21} color={theme.colors.danger} /><Text style={styles.signOutText}>{t('more.signOut')}</Text></Pressable></ScrollView><SettingsModal visible={settingsOpen} locale={locale} onClose={() => setSettingsOpen(false)} onLocale={setLocale} /></SafeAreaView>;
}
function Group({ rows }: { rows: [keyof typeof Ionicons.glyphMap, string, (() => void)?][] }) { return <View style={styles.card}>{rows.map(([icon, label, onPress], index) => <Pressable key={label} onPress={onPress} disabled={!onPress} accessibilityRole="button" accessibilityLabel={label} style={({ pressed }) => [styles.row, index > 0 && styles.divider, pressed && styles.pressed]}><Ionicons name={icon} size={21} color={theme.colors.primary} /><Text style={styles.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color={theme.colors.textMuted} /></Pressable>)}</View>; }
function System({ name, status, state }: { name: string; status: string; state: 'success' | 'attention' | 'pending' | 'error' | 'unknown' }) { return <View style={styles.systemRow}><Text style={styles.systemName}>{name}</Text><View style={[styles.dot, state === 'success' && styles.successDot, state === 'attention' && styles.warningDot, state === 'error' && styles.errorDot]} /><Text style={styles.systemStatus}>{status}</Text></View>; }
function SettingsModal({ visible, locale, onClose, onLocale }: { visible: boolean; locale: 'pl' | 'en'; onClose: () => void; onLocale: (locale: 'pl' | 'en') => Promise<void> }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{t('settings.title')}</Text><Pressable onPress={onClose} accessibilityRole="button" accessibilityLabel={t('common.close')} hitSlop={10}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Text style={styles.description}>{t('settings.languageDescription')}</Text><Text style={styles.languageHeading}>{t('settings.language')}</Text><LanguageRow label={t('settings.polish')} selected={locale === 'pl'} onPress={() => { void onLocale('pl').catch(() => undefined); }} /><LanguageRow label={t('settings.english')} selected={locale === 'en'} onPress={() => { void onLocale('en').catch(() => undefined); }} /></View></View></Modal>; }
function LanguageRow({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="radio" accessibilityState={{ selected }} style={styles.languageRow}><Text style={styles.languageText}>{label}</Text>{selected && <Ionicons name="checkmark" size={22} color={theme.colors.primary} />}</Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { paddingHorizontal: theme.spacing.xl, paddingTop: theme.spacing.lg, paddingBottom: theme.spacing.xxxl }, title: { color: theme.colors.textPrimary, fontSize: theme.typography.title, lineHeight: 36, fontWeight: '800', letterSpacing: -0.5, marginTop: theme.spacing.sm, marginBottom: theme.spacing.xl }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.card, borderWidth: 1, borderColor: theme.colors.borderSubtle, overflow: 'hidden' }, row: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.md, paddingHorizontal: theme.spacing.lg }, pressed: { backgroundColor: theme.colors.surfaceSecondary }, divider: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.borderSubtle }, rowText: { flex: 1, color: theme.colors.textPrimary, fontWeight: '700', fontSize: 16 }, systems: { backgroundColor: theme.colors.surfaceSecondary, borderRadius: theme.radius.card, padding: theme.spacing.lg, marginTop: theme.spacing.xl }, systemTitle: { color: theme.colors.textPrimary, fontWeight: '800', fontSize: 17, marginBottom: theme.spacing.sm }, systemRow: { flexDirection: 'row', alignItems: 'center', minHeight: 42 }, systemName: { flex: 1, color: theme.colors.textPrimary, fontWeight: '700' }, dot: { width: 8, height: 8, borderRadius: 4, marginRight: 7, backgroundColor: theme.colors.textMuted }, successDot: { backgroundColor: theme.colors.success }, warningDot: { backgroundColor: theme.colors.warning }, errorDot: { backgroundColor: theme.colors.danger }, systemStatus: { color: theme.colors.textSecondary, fontSize: 12 }, signOut: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: theme.spacing.sm, minHeight: 52, marginTop: theme.spacing.xl, borderRadius: theme.radius.control, backgroundColor: theme.colors.dangerSoft }, signOutText: { color: theme.colors.danger, fontWeight: '800' }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: theme.colors.overlay }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: theme.radius.large, borderTopRightRadius: theme.radius.large, padding: theme.spacing.xl, paddingBottom: theme.spacing.xxxl }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { color: theme.colors.textPrimary, fontSize: 22, fontWeight: '800' }, description: { color: theme.colors.textSecondary, lineHeight: 20, marginTop: theme.spacing.lg }, languageHeading: { color: theme.colors.textPrimary, fontWeight: '800', marginTop: theme.spacing.xl, marginBottom: theme.spacing.sm }, languageRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.borderSubtle }, languageText: { color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' } });
