import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../auth/AuthContext';
import { t } from '../i18n';
import { theme } from '../theme/theme';

export function MoreScreen() {
  const { signOut } = useAuth();
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{t('more.title')}</Text><Group rows={[['business-outline', t('more.company')], ['link-outline', t('more.systems')], ['settings-outline', t('more.settings')], ['download-outline', t('more.reports')], ['help-circle-outline', t('more.help')]]} /><View style={styles.systems}><Text style={styles.systemTitle}>{t('more.systems')}</Text><System name={t('more.ksef')} /><System name={t('more.bank')} /><System name={t('more.zus')} /></View><Pressable style={styles.signOut} onPress={signOut} accessibilityRole="button"><Ionicons name="log-out-outline" size={21} color={theme.colors.danger} /><Text style={styles.signOutText}>{t('more.signOut')}</Text></Pressable></ScrollView></SafeAreaView>;
}
function Group({ rows }: { rows: [keyof typeof Ionicons.glyphMap, string][] }) { return <View style={styles.card}>{rows.map(([icon, label], index) => <View key={label} style={[styles.row, index > 0 && styles.divider]}><Ionicons name={icon} size={21} color={theme.colors.primary} /><Text style={styles.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color={theme.colors.textMuted} /></View>)}</View>; }
function System({ name }: { name: string }) { return <View style={styles.systemRow}><Text style={styles.systemName}>{name}</Text><View style={[styles.dot, styles.dotOff]} /><Text style={styles.systemStatus}>{t('more.unknownStatus')}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: 20, paddingBottom: 36 }, title: { color: theme.colors.text, fontSize: 32, fontWeight: '900', marginTop: 8, marginBottom: 20 }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16 }, divider: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border }, rowText: { flex: 1, color: theme.colors.text, fontWeight: '700', fontSize: 16 }, systems: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, padding: 16, marginTop: 18 }, systemTitle: { color: theme.colors.text, fontWeight: '900', fontSize: 17, marginBottom: 8 }, systemRow: { flexDirection: 'row', alignItems: 'center', minHeight: 40 }, systemName: { flex: 1, color: theme.colors.text, fontWeight: '700' }, dot: { width: 8, height: 8, borderRadius: 4, marginRight: 7 }, dotOn: { backgroundColor: theme.colors.success }, dotOff: { backgroundColor: theme.colors.textMuted }, systemStatus: { color: theme.colors.textMuted, fontSize: 12 }, signOut: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 52, marginTop: 18, borderRadius: 999, backgroundColor: theme.colors.dangerSoft }, signOutText: { color: theme.colors.danger, fontWeight: '800' } });
