import * as React from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../auth/AuthContext';
import { t } from '../i18n';
import { useLocale } from '../i18n/LocaleContext';
import { theme } from '../theme/theme';

export function MoreScreen() {
  const { signOut } = useAuth(); const { locale, setLocale } = useLocale(); const [settingsOpen, setSettingsOpen] = React.useState(false);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{t('more.title')}</Text><Group rows={[['business-outline', t('more.company')], ['link-outline', t('more.systems')], ['settings-outline', t('more.settings'), () => setSettingsOpen(true)], ['download-outline', t('more.reports')], ['help-circle-outline', t('more.help')]]} /><View style={styles.systems}><Text style={styles.systemTitle}>{t('more.systems')}</Text><System name={t('more.ksef')} /><System name={t('more.bank')} /><System name={t('more.zus')} /></View><Pressable style={styles.signOut} onPress={signOut} accessibilityRole="button" accessibilityLabel={t('more.signOut')}><Ionicons name="log-out-outline" size={21} color={theme.colors.danger} /><Text style={styles.signOutText}>{t('more.signOut')}</Text></Pressable></ScrollView><SettingsModal visible={settingsOpen} locale={locale} onClose={() => setSettingsOpen(false)} onLocale={setLocale} /></SafeAreaView>;
}
function Group({ rows }: { rows: [keyof typeof Ionicons.glyphMap, string, (() => void)?][] }) { return <View style={styles.card}>{rows.map(([icon, label, onPress], index) => <Pressable key={label} onPress={onPress} disabled={!onPress} accessibilityRole="button" accessibilityLabel={label} style={[styles.row, index > 0 && styles.divider]}><Ionicons name={icon} size={21} color={theme.colors.primary} /><Text style={styles.rowText}>{label}</Text><Ionicons name="chevron-forward" size={18} color={theme.colors.textMuted} /></Pressable>)}</View>; }
function System({ name }: { name: string }) { return <View style={styles.systemRow}><Text style={styles.systemName}>{name}</Text><View style={styles.dot} /><Text style={styles.systemStatus}>{t('more.unknownStatus')}</Text></View>; }
function SettingsModal({ visible, locale, onClose, onLocale }: { visible: boolean; locale: 'pl' | 'en'; onClose: () => void; onLocale: (locale: 'pl' | 'en') => Promise<void> }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{t('settings.title')}</Text><Pressable onPress={onClose} accessibilityRole="button" accessibilityLabel={t('common.close')} hitSlop={10}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Text style={styles.description}>{t('settings.languageDescription')}</Text><Text style={styles.languageHeading}>{t('settings.language')}</Text><LanguageRow label={t('settings.polish')} selected={locale === 'pl'} onPress={() => void onLocale('pl')} /><LanguageRow label={t('settings.english')} selected={locale === 'en'} onPress={() => void onLocale('en')} /></View></View></Modal>; }
function LanguageRow({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="radio" accessibilityState={{ selected }} style={styles.languageRow}><Text style={styles.languageText}>{label}</Text>{selected && <Ionicons name="checkmark" size={22} color={theme.colors.primary} />}</Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: 20, paddingBottom: 36 }, title: { color: theme.colors.text, fontSize: 32, fontWeight: '900', marginTop: 8, marginBottom: 20 }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16 }, divider: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border }, rowText: { flex: 1, color: theme.colors.text, fontWeight: '700', fontSize: 16 }, systems: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, padding: 16, marginTop: 18 }, systemTitle: { color: theme.colors.text, fontWeight: '900', fontSize: 17, marginBottom: 8 }, systemRow: { flexDirection: 'row', alignItems: 'center', minHeight: 40 }, systemName: { flex: 1, color: theme.colors.text, fontWeight: '700' }, dot: { width: 8, height: 8, borderRadius: 4, marginRight: 7, backgroundColor: theme.colors.textMuted }, systemStatus: { color: theme.colors.textMuted, fontSize: 12 }, signOut: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 52, marginTop: 18, borderRadius: 999, backgroundColor: theme.colors.dangerSoft }, signOutText: { color: theme.colors.danger, fontWeight: '800' }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000055' }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, paddingBottom: 34 }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { color: theme.colors.text, fontSize: 22, fontWeight: '900' }, description: { color: theme.colors.textMuted, marginTop: 18 }, languageHeading: { color: theme.colors.text, fontWeight: '800', marginTop: 20, marginBottom: 4 }, languageRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border }, languageText: { color: theme.colors.text, fontSize: 16, fontWeight: '700' } });
