import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { createAccountingRepository } from '../api/config';
import { useAccountingMonth } from '../navigation/AccountingMonthContext';
import { PaymentLine } from '../model/accounting';
import { formatMoney } from '../utils/money';
import { theme } from '../theme/theme';

export function PaymentsScreen() {
  const repository = useMemo(() => createAccountingRepository(), []);
  const { month } = useAccountingMonth();
  const [payments, setPayments] = useState<PaymentLine[]>([]);
  const [selected, setSelected] = useState<PaymentLine | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setLoading(true); setError(null); repository.getMonth(month).then((value) => { if (active) setPayments(value.payments); }).catch(() => { if (active) setError('Payments could not be loaded'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [month, repository]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Payments</Text><Text style={styles.month}>{month}</Text>{loading ? <ActivityIndicator style={styles.loader} color={theme.colors.primary} /> : error ? <Text style={styles.error}>{error}</Text> : payments.length === 0 ? <Text style={styles.empty}>No payments for this month.</Text> : <View style={styles.card}>{payments.map((payment, index) => <Pressable key={payment.id} onPress={() => setSelected(payment)} style={[styles.row, index < payments.length - 1 && styles.divider]}><View style={styles.icon}><Ionicons name="card-outline" size={21} color={theme.colors.primary} /></View><View style={styles.copy}><Text style={styles.rowTitle}>{payment.title}</Text><Text style={styles.subtitle}>Due {payment.dueDate}</Text></View><View style={styles.amount}><Text style={styles.amountText}>{formatMoney(payment.outstandingAmount)}</Text><Text style={[styles.status, payment.status.toUpperCase() === 'PAID' && styles.paid]}>{payment.status.replaceAll('_', ' ')}</Text></View><Ionicons name="chevron-forward" size={18} color={theme.colors.textMuted} /></Pressable>)}</View>}</ScrollView><PaymentDetails payment={selected} onClose={() => setSelected(null)} /></SafeAreaView>;
}

function PaymentDetails({ payment, onClose }: { payment: PaymentLine | null; onClose: () => void }) { if (!payment) return null; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>Payment details</Text><Pressable onPress={onClose} accessibilityLabel="Close"><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Text style={styles.detailTitle}>{payment.title}</Text><Detail label="Status" value={payment.status.replaceAll('_', ' ')} /><Detail label="Due date" value={payment.dueDate} /><Detail label="Amount" value={formatMoney(payment.amount)} /><Detail label="Paid" value={formatMoney(payment.paidAmount)} /><Detail label="Outstanding" value={formatMoney(payment.outstandingAmount)} /><Text style={styles.readOnly}>Payment actions will be enabled when write access is available.</Text><Pressable style={styles.closeButton} onPress={onClose}><Text style={styles.closeText}>Done</Text></Pressable></View></View></Modal>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: theme.spacing.lg, paddingBottom: 32 }, title: { color: theme.colors.text, fontSize: 32, fontWeight: '900', marginTop: 12 }, month: { color: theme.colors.textMuted, fontWeight: '700', marginTop: 4, marginBottom: 20 }, loader: { marginTop: 36 }, error: { color: theme.colors.danger, marginTop: 24 }, empty: { color: theme.colors.textMuted, textAlign: 'center', marginTop: 32 }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, icon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.primarySoft }, copy: { flex: 1 }, rowTitle: { color: theme.colors.text, fontSize: 15, fontWeight: '800' }, subtitle: { color: theme.colors.textMuted, fontSize: 12, marginTop: 3 }, amount: { alignItems: 'flex-end' }, amountText: { color: theme.colors.text, fontWeight: '800' }, status: { color: theme.colors.warning, fontSize: 11, fontWeight: '800', marginTop: 3 }, paid: { color: theme.colors.success }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000055' }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, gap: 10 }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sheetTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '900' }, detailTitle: { color: theme.colors.text, fontSize: 21, fontWeight: '900' }, detail: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border, paddingVertical: 8 }, label: { color: theme.colors.textMuted, fontSize: 12 }, value: { color: theme.colors.text, fontWeight: '700', marginTop: 2 }, readOnly: { color: theme.colors.textMuted, fontSize: 12 }, closeButton: { alignItems: 'center', borderRadius: 999, backgroundColor: theme.colors.primary, paddingVertical: 12, marginTop: 4 }, closeText: { color: '#fff', fontWeight: '800' } });
