import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { createAccountingRepository } from '../api/config';
import { PaymentHistoryLine, PaymentLine } from '../model/accounting';
import { formatDate, formatMonth, paymentLabel, paymentStatusLabel, t } from '../i18n';
import { formatMoney } from '../utils/money';
import { statusForPayment } from '../presentation/accounting';
import { theme } from '../theme/theme';
import { useAccountingMonth } from '../navigation/AccountingMonthContext';
import { MonthSelector } from '../components/MonthSelector';
import { useLocale } from '../i18n/LocaleContext';

type Filter = 'ALL' | 'RYCZALT' | 'VAT' | 'ZUS';
export function PaymentsScreen() {
  useLocale();
  const repository = useMemo(() => createAccountingRepository(), []); const [payments, setPayments] = useState<PaymentLine[]>([]); const [history, setHistory] = useState<PaymentHistoryLine[]>([]); const [total, setTotal] = useState<PaymentLine['amount'] | null>(null); const [filter, setFilter] = useState<Filter>('ALL'); const [obligationsLoading, setObligationsLoading] = useState(true); const [obligationsError, setObligationsError] = useState(false); const [historyLoading, setHistoryLoading] = useState(true); const [historyError, setHistoryError] = useState(false); const [historyRetry, setHistoryRetry] = useState(0); const [obligationsRetry, setObligationsRetry] = useState(0); const [selected, setSelected] = useState<PaymentLine | null>(null); const { month, refreshVersion } = useAccountingMonth();
  useEffect(() => { let active = true; setObligationsLoading(true); setObligationsError(false); setPayments([]); setTotal(null); repository.getMonth(month).then((value) => { if (active) { setPayments(value.payments); setTotal(value.totalToPay); } }).catch(() => active && setObligationsError(true)).finally(() => active && setObligationsLoading(false)); return () => { active = false; }; }, [repository, month, refreshVersion, obligationsRetry]);
  useEffect(() => { let active = true; setHistoryLoading(true); setHistoryError(false); setHistory([]); repository.getPaymentHistory(month, filter === 'ALL' ? undefined : filter).then((value) => active && setHistory(value)).catch(() => active && setHistoryError(true)).finally(() => active && setHistoryLoading(false)); return () => { active = false; }; }, [repository, month, filter, refreshVersion, historyRetry]);
  const visible = payments.filter((item) => filter === 'ALL' || item.title.toUpperCase() === filter);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{t('settlements.title')}</Text><MonthSelector loading={obligationsLoading || historyLoading} /><Text style={styles.section}>{t('settlements.upcoming')}</Text>{total && <Text style={styles.total}>{formatMoney(total)}</Text>}<View style={styles.chips}>{(['ALL', 'RYCZALT', 'VAT', 'ZUS'] as const).map((value) => <Pressable key={value} style={[styles.chip, filter === value && styles.active]} onPress={() => setFilter(value)} accessibilityRole="button"><Text style={[styles.chipText, filter === value && styles.activeText]}>{value === 'ALL' ? t('common.all') : paymentLabel(value)}</Text></Pressable>)}</View>{obligationsLoading ? <ActivityIndicator style={styles.loader} color={theme.colors.primary} /> : obligationsError ? <RetryState message={t('common.unavailable')} onPress={() => setObligationsRetry((value) => value + 1)} /> : visible.length === 0 ? <Text style={styles.empty}>{t('settlements.noPayments')}</Text> : <View style={styles.card}>{visible.map((payment, index) => <PaymentRow key={`${payment.id}-${index}`} payment={payment} last={index === visible.length - 1} onPress={() => setSelected(payment)} />)}</View>}<Text style={styles.section}>{t('settlements.history')}</Text>{historyLoading ? <ActivityIndicator style={styles.loader} color={theme.colors.primary} /> : historyError ? <RetryState message={t('settlements.historyError')} onPress={() => setHistoryRetry((value) => value + 1)} /> : history.length === 0 ? <Text style={styles.note}>{t('settlements.noHistory')}</Text> : <View style={styles.card}>{history.map((payment, index) => <PaymentRow key={`${payment.id}-${index}`} payment={payment} last={index === history.length - 1} onPress={() => setSelected(payment)} />)}</View>}</ScrollView><PaymentDetails payment={selected} onClose={() => setSelected(null)} /></SafeAreaView>;
}
function RetryState({ message, onPress }: { message: string; onPress: () => void }) { return <View style={{ marginTop: 18 }}><Text style={styles.error}>{message}</Text><Pressable onPress={onPress} accessibilityRole="button"><Text style={{ color: theme.colors.primary, fontWeight: '800', marginTop: 8 }}>{t('common.retry')}</Text></Pressable></View>; }
function PaymentRow({ payment, last, onPress }: { payment: PaymentLine; last: boolean; onPress: () => void }) { const state = statusForPayment(payment); return <Pressable onPress={onPress} style={[styles.row, !last && styles.divider]} accessibilityRole="button" accessibilityLabel={`${paymentLabel(payment.title)}, ${paymentStatusLabel(payment.status)}`}><View style={[styles.icon, state === 'error' && styles.errorIcon]}><Ionicons name="card-outline" size={20} color={state === 'error' ? theme.colors.danger : theme.colors.primary} /></View><View style={styles.copy}><Text style={styles.rowTitle}>{paymentLabel(payment.title)}</Text><Text style={styles.subtitle}>{t('settlements.period')}: {formatMonth(payment.period ?? '')}</Text><Text style={styles.subtitle}>{t('settlements.dueDate')}: {formatDate(payment.dueDate)}</Text></View><View style={styles.amount}><Text style={styles.amountText}>{formatMoney(payment.outstandingAmount)}</Text><Text style={[styles.status, state === 'resolved' && styles.paid, state === 'error' && styles.overdue]}>{paymentStatusLabel(payment.status)}</Text></View></Pressable>; }
function PaymentDetails({ payment, onClose }: { payment: PaymentLine | null; onClose: () => void }) { if (!payment) return null; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{paymentLabel(payment.title)}</Text><Pressable onPress={onClose} accessibilityLabel={t('common.close')}><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Detail label={t('settlements.period')} value={formatMonth(payment.period ?? '')} /><Detail label={t('settlements.amount')} value={formatMoney(payment.amount)} /><Detail label={t('settlements.paidAmount')} value={formatMoney(payment.paidAmount)} /><Detail label={t('settlements.remaining')} value={formatMoney(payment.outstandingAmount)} /><Detail label={t('settlements.dueDate')} value={formatDate(payment.dueDate)} /><Detail label={t('settlements.status')} value={paymentStatusLabel(payment.status)} /></View></View></Modal>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.subtitle}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: 20, paddingBottom: 36 }, title: { color: theme.colors.text, fontSize: 32, fontWeight: '900', marginTop: 8, marginBottom: 14 }, section: { color: theme.colors.text, fontSize: 19, fontWeight: '900', marginTop: 26, marginBottom: 10 }, total: { color: theme.colors.text, fontSize: 28, fontWeight: '900', marginBottom: 12 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9 }, active: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary }, chipText: { color: theme.colors.textMuted, fontWeight: '700' }, activeText: { color: '#fff' }, loader: { marginTop: 38 }, error: { color: theme.colors.danger, marginTop: 26 }, empty: { color: theme.colors.textMuted, marginTop: 18 }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 13 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, icon: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, errorIcon: { backgroundColor: theme.colors.dangerSoft }, copy: { flex: 1 }, rowTitle: { color: theme.colors.text, fontWeight: '800' }, subtitle: { color: theme.colors.textMuted, fontSize: 12, marginTop: 3 }, amount: { alignItems: 'flex-end' }, amountText: { color: theme.colors.text, fontWeight: '800' }, status: { color: theme.colors.warning, fontSize: 11, fontWeight: '800', marginTop: 4 }, paid: { color: theme.colors.success }, overdue: { color: theme.colors.danger }, note: { color: theme.colors.textMuted, lineHeight: 20 }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000055' }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, gap: 12 }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sheetTitle: { color: theme.colors.text, fontSize: 21, fontWeight: '900' }, detail: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border, paddingVertical: 8 }, detailValue: { color: theme.colors.text, fontWeight: '800', marginTop: 3 } });
