import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { createAccountingRepository, DEFAULT_ACCOUNTING_MONTH } from '../api/config';
import { AccountingIssue } from '../model/accounting';
import { ApiError, ConfigurationError } from '../api/client';
import { theme } from '../theme/theme';

export function TasksScreen() {
  const repository = useMemo(() => createAccountingRepository(), []);
  const [month, setMonth] = useState(DEFAULT_ACCOUNTING_MONTH);
  const [issues, setIssues] = useState<AccountingIssue[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setLoading(true); setError(null); repository.getMonth(month).then((value) => { if (active) setIssues(value.issues.filter((issue) => issue.kind.toUpperCase() !== 'INFO')); }).catch((reason: unknown) => { if (active) setError(reason instanceof ConfigurationError ? 'Accounting API configuration is invalid' : reason instanceof ApiError ? reason.message : 'Tasks could not be loaded'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [month, repository]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.title}>Tasks</Text><Text style={styles.count}>{issues.length}</Text></View><View style={styles.monthRow}><Pressable onPress={() => setMonth(shiftMonth(month, -1))}><Ionicons name="chevron-back" size={20} color={theme.colors.text} /></Pressable><Text style={styles.monthLabel}>{month}</Text><Pressable onPress={() => setMonth(shiftMonth(month, 1))}><Ionicons name="chevron-forward" size={20} color={theme.colors.text} /></Pressable></View>{loading ? <ActivityIndicator style={styles.loader} color={theme.colors.primary} /> : error ? <Text style={styles.error}>{error}</Text> : issues.length === 0 ? <View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={34} color={theme.colors.success} /><Text style={styles.emptyTitle}>No open accounting tasks</Text><Text style={styles.emptyText}>The backend reported no issues requiring attention for this month.</Text></View> : <View style={styles.card}>{issues.map((issue, index) => <TaskRow issue={issue} key={issue.id} last={index === issues.length - 1} />)}</View>}</ScrollView></SafeAreaView>;
}
function TaskRow({ issue, last }: { issue: AccountingIssue; last: boolean }) { return <Pressable style={[styles.row, !last && styles.divider]} onPress={() => {}}><View style={styles.icon}><Ionicons name="alert-circle-outline" size={21} color={theme.colors.warning} /></View><View style={styles.copy}><Text style={styles.rowTitle}>{issue.title}</Text><Text style={styles.rowText}>{issue.message}</Text>{issue.sourceReference ? <Text style={styles.source}>{issue.sourceReference}</Text> : null}<Text style={styles.action}>{issue.resolution.actionLabel ?? issue.resolution.command ?? 'Review details'} ›</Text></View></Pressable>; }
function shiftMonth(month: string, offset: number) { const date = new Date(`${month}-01T00:00:00Z`); date.setUTCMonth(date.getUTCMonth() + offset); return date.toISOString().slice(0, 7); }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: theme.spacing.lg, paddingBottom: 32 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 12 }, title: { fontSize: 32, fontWeight: '900', color: theme.colors.text }, count: { minWidth: 30, textAlign: 'center', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, backgroundColor: theme.colors.warningSoft, color: theme.colors.warning, fontWeight: '900' }, monthRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 10, borderRadius: theme.radius.md, backgroundColor: theme.colors.surface, marginBottom: 16 }, monthLabel: { color: theme.colors.text, fontSize: 16, fontWeight: '800' }, loader: { marginTop: 36 }, error: { color: theme.colors.danger, marginTop: 24 }, empty: { alignItems: 'center', marginTop: 48, gap: 8 }, emptyTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '800' }, emptyText: { color: theme.colors.textMuted, textAlign: 'center', lineHeight: 21 }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { flexDirection: 'row', gap: 12, padding: 14 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, icon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.warningSoft }, copy: { flex: 1, gap: 4 }, rowTitle: { color: theme.colors.text, fontSize: 15, fontWeight: '800' }, rowText: { color: theme.colors.textMuted, lineHeight: 19 }, source: { color: theme.colors.textMuted, fontSize: 12 }, action: { color: theme.colors.primary, fontWeight: '800', marginTop: 4 } });
