import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { createAccountingRepository } from '../api/config';
import { AccountingIssue } from '../model/accounting';
import { ApiError, ConfigurationError } from '../api/client';
import { theme } from '../theme/theme';
import { useRoute, type RouteProp } from '@react-navigation/native';
import type { AppTabParamList } from '../navigation/AppNavigator';
import { useAccountingMonth } from '../navigation/AccountingMonthContext';

export function TasksScreen() {
  const repository = useMemo(() => createAccountingRepository(), []);
  const { month, setMonth } = useAccountingMonth();
  const route = useRoute<RouteProp<AppTabParamList, 'Tasks'>>();
  const [issues, setIssues] = useState<AccountingIssue[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setLoading(true); setError(null); repository.getMonth(month).then((value) => { if (active) setIssues(value.issues.filter((issue) => issue.kind.toUpperCase() !== 'INFO')); }).catch((reason: unknown) => { if (active) setError(reason instanceof ConfigurationError ? 'Accounting API configuration is invalid' : reason instanceof ApiError ? reason.message : 'Tasks could not be loaded'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [month, repository]);
  const visibleIssues = route.params?.attentionOnly ? issues.filter((issue) => issue.severity.toUpperCase() !== 'INFO') : issues;
  const [selected, setSelected] = useState<AccountingIssue | null>(null);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.title}>Tasks</Text><Text style={styles.count}>{visibleIssues.length}</Text></View><View style={styles.monthRow}><Pressable onPress={() => setMonth(shiftMonth(month, -1))} accessibilityLabel="Previous month"><Ionicons name="chevron-back" size={20} color={theme.colors.text} /></Pressable><Text style={styles.monthLabel}>{month}</Text><Pressable onPress={() => setMonth(shiftMonth(month, 1))} accessibilityLabel="Next month"><Ionicons name="chevron-forward" size={20} color={theme.colors.text} /></Pressable></View>{loading ? <ActivityIndicator style={styles.loader} color={theme.colors.primary} /> : error ? <Text style={styles.error}>{error}</Text> : visibleIssues.length === 0 ? <View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={34} color={theme.colors.success} /><Text style={styles.emptyTitle}>No open accounting tasks</Text><Text style={styles.emptyText}>The backend reported no issues requiring attention for this month.</Text></View> : <View style={styles.card}>{visibleIssues.map((issue, index) => <TaskRow issue={issue} key={issue.id} last={index === visibleIssues.length - 1} onPress={() => setSelected(issue)} />)}</View>}</ScrollView><TaskDetails issue={selected} onClose={() => setSelected(null)} /></SafeAreaView>;
}
function TaskRow({ issue, last, onPress }: { issue: AccountingIssue; last: boolean; onPress: () => void }) { return <Pressable style={[styles.row, !last && styles.divider]} onPress={onPress}><View style={styles.icon}><Ionicons name="alert-circle-outline" size={21} color={theme.colors.warning} /></View><View style={styles.copy}><Text style={styles.rowTitle}>{issue.title}</Text><Text style={styles.rowText}>{issue.message}</Text>{issue.sourceReference ? <Text style={styles.source}>{issue.sourceReference}</Text> : null}<Text style={styles.action}>{issue.resolution.actionLabel ?? issue.resolution.command ?? 'Review details'} ›</Text></View></Pressable>; }
function TaskDetails({ issue, onClose }: { issue: AccountingIssue | null; onClose: () => void }) { if (!issue) return null; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>Resolve task</Text><Pressable onPress={onClose} accessibilityLabel="Close"><Ionicons name="close" size={24} color={theme.colors.text} /></Pressable></View><Text style={styles.detailTitle}>{issue.title}</Text><Text style={styles.detailText}>{issue.message}</Text>{issue.resolution.options.map((option) => <View key={option.value} style={styles.option}><Text style={styles.optionLabel}>{option.label}</Text>{option.recommended ? <Text style={styles.recommended}>Recommended</Text> : null}</View>)}{issue.resolution.settingsPath ? <Text style={styles.source}>Settings: {issue.resolution.settingsPath}</Text> : null}<Text style={styles.readOnly}>Resolution actions will be enabled when write access is available.</Text><Pressable style={styles.closeButton} onPress={onClose}><Text style={styles.closeText}>Done</Text></Pressable></View></View></Modal>; }
function shiftMonth(month: string, offset: number) { const date = new Date(`${month}-01T00:00:00Z`); date.setUTCMonth(date.getUTCMonth() + offset); return date.toISOString().slice(0, 7); }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: theme.spacing.lg, paddingBottom: 32 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 12 }, title: { fontSize: 32, fontWeight: '900', color: theme.colors.text }, count: { minWidth: 30, textAlign: 'center', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, backgroundColor: theme.colors.warningSoft, color: theme.colors.warning, fontWeight: '900' }, monthRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 10, borderRadius: theme.radius.md, backgroundColor: theme.colors.surface, marginBottom: 16 }, monthLabel: { color: theme.colors.text, fontSize: 16, fontWeight: '800' }, loader: { marginTop: 36 }, error: { color: theme.colors.danger, marginTop: 24 }, empty: { alignItems: 'center', marginTop: 48, gap: 8 }, emptyTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '800' }, emptyText: { color: theme.colors.textMuted, textAlign: 'center', lineHeight: 21 }, card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, overflow: 'hidden' }, row: { flexDirection: 'row', gap: 12, padding: 14 }, divider: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, icon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.warningSoft }, copy: { flex: 1, gap: 4 }, rowTitle: { color: theme.colors.text, fontSize: 15, fontWeight: '800' }, rowText: { color: theme.colors.textMuted, lineHeight: 19 }, source: { color: theme.colors.textMuted, fontSize: 12 }, action: { color: theme.colors.primary, fontWeight: '800', marginTop: 4 }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#00000055' }, sheet: { backgroundColor: theme.colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, gap: 10 }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sheetTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '900' }, detailTitle: { color: theme.colors.text, fontSize: 21, fontWeight: '900' }, detailText: { color: theme.colors.textMuted, lineHeight: 20 }, option: { padding: 12, borderRadius: 10, backgroundColor: theme.colors.surfaceMuted }, optionLabel: { color: theme.colors.text, fontWeight: '700' }, recommended: { color: theme.colors.success, fontSize: 12, marginTop: 3, fontWeight: '800' }, readOnly: { color: theme.colors.textMuted, fontSize: 12 }, closeButton: { alignItems: 'center', borderRadius: 999, backgroundColor: theme.colors.primary, paddingVertical: 12, marginTop: 4 }, closeText: { color: '#fff', fontWeight: '800' } });
