package com.smartbox.investory.ryczalt.calculation;

public enum InputChange {
  INCOME_INVOICE_CHANGED,
  COST_INVOICE_CHANGED,
  ZUS_INPUT_CHANGED,
  RYCZALT_DEDUCTIONS_CHANGED,
  VAT_ADJUSTMENT_CHANGED,
  FX_FACT_CHANGED,
  TRANSACTION_CHANGED
}
