import { describe, expect, it } from 'vitest';
import { decimalString, mapCounterparty, mapCounterpartyRule, mapInvoice, mapPeriod } from './accountingMapper';

const period = { month: '2026-09', status: 'OPEN', calculations: [{ type: 'RYCZALT', status: 'CALCULATED', amount: '1440.00' }], summary: { revenue: '12000.00', ryczalt: '1440.00', vat: '2000.00', zus: '1495.04' }, documents: { invoiceCount: 1, transactionCount: 1 }, settlement: { expectedCount: 3, paidCount: 1, outstandingCount: 2, totalExpected: '4935.04', totalPaid: '2000.00', totalOutstanding: '2935.04', fullySettled: false }, reconciliation: { rowCount: 15, settledCount: 12, mismatchCount: 1, missingEvidenceCount: 2 }, completeness: { status: 'COMPLETE', blockingIssueCount: 0 }, allowedActions: [] };
const invoice = { id: 1, direction: 'COST', reference: 'FV/1', issueDate: '2026-09-01', accountingDate: '2026-09-01', netAmount: '100.00', vatAmount: '23.45', grossAmount: '123.45', currency: 'PLN', bookedNetPln: '100.00', ryczaltRate: '0.00', deductibleVat: '11.73', classification: 'FUEL', counterparty: { id: 7, legalName: 'Orlen', alias: 'Orlen fuel', taxIdentifier: '1234567890' }, approvalStatus: 'APPROVED', approvalMethod: 'COUNTERPARTY_RULE', paymentVerificationPolicy: 'NOT_REQUIRED', paymentStatus: 'NOT_REQUIRED', sourceType: 'KSEF', sourceReference: 'KSEF-2026-001' };

describe('canonical accounting mappers', () => {
  it('accepts exact signed decimal strings and rejects legacy numeric/malformed values', () => { expect(decimalString('1234567.89')).toBe('1234567.89'); expect(decimalString('-7636.0000')).toBe('-7636.0000'); expect(() => decimalString('1e3')).toThrow(); expect(() => decimalString('NaN')).toThrow(); expect(() => decimalString('Infinity')).toThrow(); expect(() => decimalString(1 as never)).toThrow(); });
  it('maps exact calculation amounts separately from settlement, completeness and reconciliation', () => { const mapped = mapPeriod(period, [invoice], [], [], [{ id: 'x', code: 'UNKNOWN', severity: 'WARNING', kind: 'FUTURE_KIND', title: null, message: null, sourceReference: null }]); expect(mapped.calculations).toEqual([{ type: 'RYCZALT', status: 'CALCULATED', amount: { amount: '1440.00', currency: null } }]); expect(mapped.settlement.totalOutstanding.amount).toBe('2935.04'); expect(mapped.completeness.status).toBe('COMPLETE'); expect(mapped.settlement.fullySettled).toBe(false); expect(mapped.issues[0]?.kind).toBe('FUTURE_KIND'); expect(mapped.reconciliation.state).toBe('missing_evidence'); });
  it('maps exact invoice money, provenance, classification, tax identifier and canonical enums', () => { const mapped = mapInvoice(invoice); expect(mapped.documentNumber).toBe('FV/1'); expect(mapped.amount.amount).toBe('123.45'); expect(mapped.direction).toBe('PURCHASE'); expect(mapped.paymentStatus).toBe('NOT_REQUIRED'); expect(mapped.sourceType).toBe('KSEF'); expect(mapped.source).toBe('KSEF-2026-001'); expect(mapped.category).toBe('FUEL'); expect(mapped.taxIdentifier).toBe('1234567890'); expect(mapCounterparty({ id: 1, legalName: 'Orlen', alias: null, taxIdentifier: null, country: 'PL' }).displayName).toBe('Orlen'); });
  it('maps multiple counterparty rule decisions without translating or inferring backend values', () => { const mapped = mapCounterpartyRule({ id: 9, name: 'Fuel', sourceType: 'UPLOAD', documentType: 'INVOICE', serviceKey: 'FUEL', classification: 'VEHICLE_FUEL', vatTreatment: 'DOMESTIC', vatDeductionRatio: '50.00', ryczaltRate: null, autoApprove: true, paymentVerificationPolicy: 'NOT_REQUIRED' }); expect(mapped).toMatchObject({ id: '9', name: 'Fuel', classification: 'VEHICLE_FUEL', vatDeductionRatio: '50.00', autoApprove: true, paymentVerificationPolicy: 'NOT_REQUIRED' }); });
});
