import { describe, expect, it } from 'vitest';
import { decimalString, mapCounterparty, mapInvoice, mapPeriod } from './accountingMapper';

const period = { month: '2026-09', status: 'OPEN', calculations: [], summary: { revenue: '12000.00', ryczalt: '1440.00', vat: '2000.00', zus: '1495.04' }, documents: { invoiceCount: 1, transactionCount: 1 }, settlement: { expectedCount: 3, paidCount: 1, outstandingCount: 2, totalExpected: '4935.04', totalPaid: '2000.00', totalOutstanding: '2935.04', fullySettled: false }, reconciliation: { rowCount: 15, settledCount: 12, mismatchCount: 1, missingEvidenceCount: 2 }, completeness: { status: 'COMPLETE', blockingIssueCount: 0 }, allowedActions: ['SETTLE'] };
const invoice = { id: 1, direction: 'COST', reference: 'FV/1', issueDate: '2026-09-01', accountingDate: '2026-09-01', netAmount: '100.00', vatAmount: '23.45', grossAmount: '123.45', currency: 'PLN', bookedNetPln: '100.00', ryczaltRate: '0.00', deductibleVat: '11.73', counterparty: { id: 7, legalName: 'Orlen', alias: 'Orlen fuel' }, approvalStatus: 'APPROVED', approvalMethod: 'COUNTERPARTY_RULE', paymentVerificationPolicy: 'NOT_REQUIRED', paymentStatus: 'NOT_REQUIRED' };

describe('canonical accounting mappers', () => {
  it('accepts exact signed decimal strings and rejects legacy numeric/malformed values', () => { expect(decimalString('1234567.89')).toBe('1234567.89'); expect(decimalString('-7636.0000')).toBe('-7636.0000'); expect(() => decimalString('1e3')).toThrow(); expect(() => decimalString('NaN')).toThrow(); expect(() => decimalString('Infinity')).toThrow(); expect(() => decimalString(1 as never)).toThrow(); });
  it('keeps settlement, completeness and reconciliation independent', () => { const mapped = mapPeriod(period, [invoice], [], [], [{ id: 'x', code: 'UNKNOWN', severity: 'WARNING', kind: 'FUTURE_KIND', title: null, message: null, sourceReference: null }]); expect(mapped.settlement.totalOutstanding.amount).toBe('2935.04'); expect(mapped.completeness.status).toBe('COMPLETE'); expect(mapped.settlement.fullySettled).toBe(false); expect(mapped.issues[0]?.kind).toBe('FUTURE_KIND'); expect(mapped.reconciliation.state).toBe('missing_evidence'); });
  it('maps the native invoice wire shape and preserves alias fallback', () => { const mapped = mapInvoice(invoice); expect(mapped.documentNumber).toBe('FV/1'); expect(mapped.amount.amount).toBe('123.45'); expect(mapped.direction).toBe('PURCHASE'); expect(mapped.paymentStatus).toBe('NOT_REQUIRED'); expect(mapCounterparty({ id: 1, legalName: 'Orlen', alias: null, taxIdentifier: null, country: 'PL' }).displayName).toBe('Orlen'); });
});
