import { useMemo, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import { Ionicons } from '@expo/vector-icons';
import { ACCOUNTING_PROFILE_ID, createAccountingApi } from '../../api/config';
import type { CandidateDto } from '../../api/dto/accounting';
import { formatCurrency, formatDate, t } from '../../i18n';
import { isRequiredInputActive, mapCostError, mapCostMutation, mapRecognizedCost, missingRequiredInput, type CostErrorState, type CostReview } from '../../presentation/costPresentation';
import { useAccountingMonth } from '../../navigation/AccountingMonthContext';
import { theme } from '../../theme/theme';

type FileValue = { uri: string; name: string; type: string };

export function AddCostScreen({ onBack }: { onBack: () => void }) {
  const api = useMemo(() => { try { return createAccountingApi(); } catch { return null; } }, []);
  const { refreshAccounting } = useAccountingMonth();
  const [file, setFile] = useState<FileValue | null>(null); const [review, setReview] = useState<CostReview | null>(null); const [vatTreatment, setVatTreatment] = useState<string | null>(null); const [vatRate, setVatRate] = useState(''); const [country, setCountry] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<CostErrorState | 'no_document' | 'unsupported' | null>(null); const [done, setDone] = useState(false); const [duplicate, setDuplicate] = useState(false);
  async function pick() { try { const result = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'image/*'], copyToCacheDirectory: true }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; setFile({ uri: asset.uri, name: asset.name || 'document', type: asset.mimeType || 'application/octet-stream' }); setReview(null); setError(null); setDuplicate(false); } catch (reason) { setError(mapCostError(reason)); } }
  async function recognize() { if (busy) return; if (!file) return setError('no_document'); if (!api) return setError('unavailable'); setBusy(true); setError(null); try { const candidate = await api.recognizeDocument(ACCOUNTING_PROFILE_ID, file); const next = mapRecognizedCost(candidate); setReview(next); setVatTreatment(candidate.vatTreatment ?? null); setVatRate(candidate.vatRate == null ? '' : String(candidate.vatRate)); setCountry(''); setError(next.state === 'unsupported' ? 'unsupported' : next.state === 'requires_input' && next.options.length === 0 ? 'backend_required' : null); } catch (reason) { setError(mapCostError(reason)); } finally { setBusy(false); } }
  async function save() { if (busy) return; if (!review || review.state === 'unsupported' || review.state === 'duplicate' || !api) return setError(review?.options.length === 0 ? 'backend_required' : 'validation_required'); const values = { vatTreatment, vatRate: vatRate.trim() || null, counterpartyCountry: country.trim() || null }; if (review.requiredInputs.length === 0 || missingRequiredInput(review.requiredInputs, values)) return setError(review.requiredInputs.length === 0 ? 'backend_required' : 'validation_required'); const candidate: CandidateDto = review.candidate; const countryInput = review.requiredInputs.find((input) => input.field === 'counterpartyCountry'); const rateInput = review.requiredInputs.find((input) => input.field === 'vatRate'); setBusy(true); setError(null); setDuplicate(false); try { const result = await api.saveReviewedDocument(ACCOUNTING_PROFILE_ID, { sourceReference: candidate.sourceReference, documentType: candidate.documentType, issueDate: candidate.issueDate, saleDate: candidate.saleDate, dueDate: candidate.dueDate, reference: candidate.reference, counterpartyAlias: candidate.seller || candidate.buyer, counterpartyTaxIdentifier: candidate.sellerNip, counterpartyCountry: countryInput && isRequiredInputActive(countryInput, values) ? country.trim() : null, category: candidate.category, currency: candidate.currency, netAmount: candidate.netAmount, vatAmount: candidate.vatAmount, grossAmount: candidate.grossAmount, vatDeductionRatio: null, vatTreatment, note: candidate.note, taxPeriod: null, vatRate: rateInput && isRequiredInputActive(rateInput, values) ? vatRate.trim().replace(',', '.') : candidate.vatRate ?? null }); const mapped = mapCostMutation(result); if (mapped.state === 'duplicate') { setDuplicate(true); return; } if (mapped.state !== 'success') { setError('unknown_error'); return; } refreshAccounting(); setDone(true); } catch (reason) { setError(mapCostError(reason)); } finally { setBusy(false); } }
  if (done) return <Shell title={t('cost.title')} onBack={onBack}><View style={styles.success}><Ionicons name="checkmark-circle-outline" size={42} color={theme.colors.success} /><Text style={styles.successTitle}>{t('cost.saved')}</Text><Button label={t('common.close')} onPress={onBack} /></View></Shell>;
  return <Shell title={t('cost.title')} onBack={onBack}><Pressable style={styles.upload} onPress={pick} accessibilityRole="button" accessibilityLabel={t('cost.chooseDocument')}><Ionicons name="cloud-upload-outline" size={30} color={theme.colors.primary} /><Text style={styles.uploadTitle}>{file?.name || t('cost.chooseDocument')}</Text><Text style={styles.muted}>{t('cost.chooseDocumentHint')}</Text></Pressable>{file && !review ? <Button label={busy ? t('common.loading') : t('cost.recognize')} onPress={recognize} disabled={busy} /> : null}{review ? <Review review={review} duplicate={duplicate} vatTreatment={vatTreatment} vatRate={vatRate} country={country} onTreatment={setVatTreatment} onVatRate={setVatRate} onCountry={setCountry} onSave={save} busy={busy} /> : null}{error && <Text style={styles.error} accessibilityRole="alert">{errorText(error)}</Text>}</Shell>;
}

function Review({ review, duplicate, vatTreatment, vatRate, country, onTreatment, onVatRate, onCountry, onSave, busy }: { review: CostReview; duplicate: boolean; vatTreatment: string | null; vatRate: string; country: string; onTreatment: (value: string) => void; onVatRate: (value: string) => void; onCountry: (value: string) => void; onSave: () => void; busy: boolean }) { const values = { vatTreatment, vatRate: vatRate.trim() || null, counterpartyCountry: country.trim() || null }; const treatmentInput = review.requiredInputs.find((input) => input.field === 'vatTreatment'); const rateInput = review.requiredInputs.find((input) => input.field === 'vatRate'); const countryInput = review.requiredInputs.find((input) => input.field === 'counterpartyCountry'); return <View style={styles.extracted}><Text style={styles.step}>{t('cost.recognized')}</Text><Row label={t('invoices.counterparty')} value={review.supplier || t('common.unknown')} /><Row label={t('invoices.number')} value={review.documentNumber || t('common.unknown')} /><Row label={t('invoices.issueDate')} value={formatDate(review.issueDate)} /><Row label={t('invoices.currency')} value={review.currency || t('common.unknown')} /><Row label={t('invoice.total')} value={review.amount == null ? t('common.unknown') : formatCurrency(review.amount, review.currency)} />{review.state === 'unsupported' ? <Text style={styles.error}>{t('cost.unsupportedDirection')}</Text> : review.state === 'duplicate' ? <Text style={styles.notice}>{t('cost.duplicate')}</Text> : review.requiredInputs.length === 0 ? <Text style={styles.notice}>{t('cost.backendRequired')}</Text> : <>{treatmentInput && <><Text style={styles.label}>{treatmentInput.label}</Text><View style={styles.options}>{treatmentInput.options.map((option) => <Pressable key={option.value} onPress={() => onTreatment(option.value)} style={[styles.option, vatTreatment === option.value && styles.optionSelected]} accessibilityRole="radio" accessibilityState={{ selected: vatTreatment === option.value }}><Text style={[styles.optionText, vatTreatment === option.value && styles.optionSelectedText]}>{option.label}</Text></Pressable>)}</View></>}{rateInput && isRequiredInputActive(rateInput, values) && <Field label={rateInput.label} value={vatRate} onChangeText={onVatRate} keyboardType="decimal-pad" />}{countryInput && isRequiredInputActive(countryInput, values) && <Field label={countryInput.label} value={country} onChangeText={onCountry} />}{review.requiresVatDecision && !vatTreatment && <Text style={styles.notice}>{t('cost.accountingDecisionRequired')}</Text>}<Button label={busy ? t('common.loading') : t('cost.confirm')} onPress={onSave} disabled={busy} /></>}{duplicate && <Text style={styles.notice}>{t('cost.duplicate')}</Text>}</View>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.muted}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function Field({ label, value, onChangeText, keyboardType = 'default' }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'default' | 'decimal-pad' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType={keyboardType} style={styles.input} accessibilityLabel={label} /></View>; }
function Shell({ title, onBack, children }: { title: string; onBack: () => void; children: React.ReactNode }) { return <KeyboardAvoidingView style={styles.form} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={onBack} accessibilityRole="button" accessibilityLabel={t('common.back')} hitSlop={10}><Ionicons name="chevron-back" size={24} color={theme.colors.text} /></Pressable><Text style={styles.title}>{title}</Text><View style={styles.spacer} /></View>{children}</ScrollView></KeyboardAvoidingView>; }
function Button({ label, onPress, disabled }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable style={[styles.button, disabled && styles.disabled]} onPress={onPress} disabled={disabled} accessibilityRole="button"><Text style={styles.buttonText}>{label}</Text></Pressable>; }
function errorText(error: CostErrorState | 'no_document' | 'unsupported'): string { const key = error === 'no_document' ? 'cost.noDocument' : error === 'unsupported' ? 'cost.unsupportedDirection' : `cost.errors.${error}`; return t(key); }
const styles = StyleSheet.create({ form: { flex: 1, backgroundColor: theme.colors.background }, content: { padding: 20, paddingBottom: 40 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, marginBottom: 20 }, title: { color: theme.colors.text, fontSize: 22, fontWeight: '900' }, spacer: { width: 24 }, upload: { minHeight: 160, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, borderStyle: 'dashed', padding: 20 }, uploadTitle: { color: theme.colors.text, fontSize: 16, fontWeight: '800', marginTop: 10, textAlign: 'center' }, muted: { color: theme.colors.textMuted, marginTop: 3 }, button: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 999, backgroundColor: theme.colors.primary, paddingHorizontal: 18, marginTop: 15 }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 15 }, disabled: { opacity: 0.55 }, error: { color: theme.colors.danger, lineHeight: 20, marginVertical: 10 }, notice: { color: theme.colors.warning, lineHeight: 20, marginTop: 15 }, extracted: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.colors.border, padding: 15, marginTop: 20 }, step: { color: theme.colors.text, fontSize: 18, fontWeight: '900', marginBottom: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border, paddingVertical: 11 }, value: { color: theme.colors.text, fontWeight: '800', flex: 1, textAlign: 'right' }, field: { marginTop: 12 }, label: { color: theme.colors.textMuted, fontSize: 13, fontWeight: '700', marginBottom: 6 }, input: { minHeight: 48, backgroundColor: theme.colors.surface, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, paddingHorizontal: 13, color: theme.colors.text, fontSize: 16 }, options: { gap: 8 }, option: { minHeight: 44, justifyContent: 'center', borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, paddingHorizontal: 12 }, optionSelected: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primarySoft }, optionText: { color: theme.colors.textMuted, fontWeight: '700' }, optionSelectedText: { color: theme.colors.primary }, success: { alignItems: 'center', gap: 12, marginTop: 80 }, successTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '800', textAlign: 'center' } });
